"""Starship assimilation for Camelot shell/cockpit prompt surfaces."""

from __future__ import annotations

import json
import shutil
import subprocess
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parent.parent
STAGING_ROOT = REPO_ROOT / ".camelot" / "vault" / "staging" / "starship"
RUNTIME_DIR = REPO_ROOT / "03_VAULT" / "runtime_state" / "starship"
CONFIG_PATH = RUNTIME_DIR / "camelot-starship.toml"
POWERSHELL_SNIPPET_PATH = RUNTIME_DIR / "init_camelot_starship.ps1"
ARTIFACT_PATH = RUNTIME_DIR / "starship_assimilation_latest.json"
REPORT_PATH = REPO_ROOT / "docs" / "reports" / "starship_assimilation_feedback.md"
MODULE_SCRIPT = REPO_ROOT / "bin" / "starship_camelot_module.py"


def _run_capture(args: list[str], *, cwd: Path = REPO_ROOT, timeout: int = 10) -> dict[str, Any]:
    try:
        result = subprocess.run(args, cwd=str(cwd), capture_output=True, text=True, timeout=timeout, shell=False)
        return {
            "ok": result.returncode == 0,
            "returncode": result.returncode,
            "stdout": result.stdout.strip(),
            "stderr": result.stderr.strip(),
        }
    except Exception as exc:  # pragma: no cover - environment-specific
        return {"ok": False, "error": f"{type(exc).__name__}: {exc}"}


def detect_starship() -> dict[str, Any]:
    executable = shutil.which("starship")
    payload: dict[str, Any] = {"present": executable is not None, "path": executable}
    if executable:
        payload["version"] = _run_capture([executable, "--version"])
    return payload


def staged_source_status() -> dict[str, Any]:
    if not STAGING_ROOT.exists():
        return {"present": False, "path": str(STAGING_ROOT)}
    head = _run_capture(["git", "rev-parse", "HEAD"], cwd=STAGING_ROOT)
    status = _run_capture(["git", "status", "--short"], cwd=STAGING_ROOT)
    return {
        "present": True,
        "path": str(STAGING_ROOT),
        "head": head.get("stdout") if head.get("ok") else None,
        "dirty": bool(str(status.get("stdout", "")).strip()),
    }


def starship_config_text(module_script: Path = MODULE_SCRIPT) -> str:
    command = str(module_script).replace("\\", "\\\\")
    return f'''# Camelot-OS Starship prompt profile
# Generated by: python -m control_plane.camelot_cli starship assimilate
# Activation is explicit. Set STARSHIP_CONFIG to this file, then run starship init.

add_newline = false
scan_timeout = 30
command_timeout = 900
format = "$directory$git_branch$git_status$python$rust$nodejs$custom.camelot$line_break$character"

[character]
success_symbol = "[CAMELOT>](bold green)"
error_symbol = "[CAMELOT!](bold red)"

[directory]
truncation_length = 4
style = "bold cyan"

[git_branch]
symbol = "git:"
style = "bold yellow"

[git_status]
style = "yellow"

[python]
symbol = "py:"
style = "green"

[rust]
symbol = "rs:"
style = "red"

[nodejs]
symbol = "node:"
style = "green"

[custom.camelot]
command = "python {command}"
when = "python {command} --available"
format = " [$output](bold blue)"
description = "Camelot cockpit health summary"
'''


def powershell_snippet(config_path: Path = CONFIG_PATH) -> str:
    escaped = str(config_path).replace("'", "''")
    return f'''# CAMELOT-OS Starship prompt integration
# Source this from PowerShell after installing Starship.
# Official init form: Invoke-Expression (&starship init powershell)
$env:STARSHIP_CONFIG = '{escaped}'
if (Get-Command starship -ErrorAction SilentlyContinue) {{
    Invoke-Expression (&starship init powershell)
}} else {{
    Write-Warning 'Starship executable not found. Install Starship, then re-source this file.'
}}
'''


def render_markdown(payload: dict[str, Any]) -> str:
    starship = payload["starship"]
    source = payload["source"]
    lines = [
        "# Starship Assimilation Feedback",
        "",
        f"- Generated UTC: {payload['generated_utc']}",
        f"- State: {payload['state']}",
        f"- Starship Present: {starship.get('present')}",
        f"- Staged Source Present: {source.get('present')}",
        f"- Staged Source HEAD: {source.get('head')}",
        "",
        "## Artifacts",
        f"- Config: `{payload['config_path']}`",
        f"- PowerShell snippet: `{payload['powershell_snippet_path']}`",
        f"- Cockpit module: `{payload['module_script']}`",
        "",
        "## Feedback",
    ]
    for item in payload["feedback"]:
        lines.append(f"- {item}")
    lines.extend([
        "",
        "## Activation",
        "```powershell",
        f". '{payload['powershell_snippet_path']}'",
        "```",
        "",
        "No shell profile was modified by this assimilation pass.",
        "",
    ])
    return "\n".join(lines)


def run_starship_assimilation(*, write: bool = True) -> dict[str, Any]:
    starship = detect_starship()
    source = staged_source_status()
    feedback = [
        "Starship is a strong fit for Camelot cockpit UX because it is cross-shell, fast, and config-driven.",
        "Use STARSHIP_CONFIG instead of overwriting the user's global ~/.config/starship.toml.",
        "Keep Camelot state in one custom module so Starship stays a prompt renderer, not an execution orchestrator.",
        "Do not auto-edit PowerShell profiles; provide a snippet and let the operator opt in.",
    ]
    if not starship.get("present"):
        feedback.append("Starship executable is not currently on PATH; generated config is ready but inactive until installed.")
    if not source.get("present"):
        feedback.append("Starship source is not staged; run the assimilation clone step before source-level audits.")

    state = "STARSHIP_READY" if starship.get("present") and source.get("present") else "STARSHIP_STAGED"
    payload: dict[str, Any] = {
        "schema": "camelot.starship-assimilation/v1",
        "generated_utc": datetime.now(timezone.utc).isoformat(),
        "state": state,
        "upstream": "https://github.com/starship/starship",
        "docs_source": "/websites/starship_rs via Context7",
        "starship": starship,
        "source": source,
        "config_path": str(CONFIG_PATH),
        "powershell_snippet_path": str(POWERSHELL_SNIPPET_PATH),
        "module_script": str(MODULE_SCRIPT),
        "feedback": feedback,
        "verification": [
            "python -m control_plane.camelot_cli starship assimilate --json",
            "python bin/starship_camelot_module.py --available",
            "python bin/starship_camelot_module.py",
        ],
    }
    if write:
        RUNTIME_DIR.mkdir(parents=True, exist_ok=True)
        REPORT_PATH.parent.mkdir(parents=True, exist_ok=True)
        CONFIG_PATH.write_text(starship_config_text(), encoding="utf-8")
        POWERSHELL_SNIPPET_PATH.write_text(powershell_snippet(), encoding="utf-8")
        ARTIFACT_PATH.write_text(json.dumps(payload, indent=2), encoding="utf-8")
        REPORT_PATH.write_text(render_markdown(payload), encoding="utf-8")
        payload["artifact_path"] = str(ARTIFACT_PATH)
        payload["report_path"] = str(REPORT_PATH)
    return payload


if __name__ == "__main__":
    print(json.dumps(run_starship_assimilation(), indent=2))