// SPDX-License-Identifier: MIT

// Parity suite for the Omni-Voice D.A.G. port.
//
// `omniVoice.crystal.json` is generated from the Python source of truth
// (control_plane/dispatch/omni_voice_dag.py). The vectors below were produced by
// the Python implementation, so replaying them here is what proves the
// TypeScript port has not drifted. If a test fails, either the port diverged or
// the fixture is stale — regenerate with:
//
//   python -m control_plane.omni_voice_dag \
//       --write-vectors apps/bifrost/src/omniVoice.crystal.json

import { describe, expect, it } from 'vitest';
import {
  CRYSTAL,
  CRYSTAL_FINGERPRINT,
  CRYSTAL_GENERATOR,
  TauPolicyError,
  detectRune,
  inferFeatures,
  resolveTau,
  routeOmniVoice,
  softmaxDispatch,
} from './omniVoice';

const EPSILON_DIGITS = 9;

describe('fixture provenance', () => {
  it('was generated by the Python source of truth', () => {
    expect(CRYSTAL.generator).toBe(CRYSTAL_GENERATOR);
    expect(CRYSTAL.fingerprint).toBe(CRYSTAL_FINGERPRINT);
    expect(CRYSTAL.systemIdentity).toBe('OMNI_VOICE_ROUTER_vMAX');
    expect(CRYSTAL.hardwareCeilingMb).toBe(384);
    expect(CRYSTAL.bypassPrefix).toBe('ᛟ_');
    expect(CRYSTAL.featureDims).toHaveLength(6);
    expect(CRYSTAL.bypassCommands).toHaveLength(5);
    expect(CRYSTAL.vectors.length).toBeGreaterThan(0);
  });

  it('carries a persona weight vector per declared feature dim', () => {
    for (const [knight, vector] of Object.entries(CRYSTAL.weights)) {
      expect(vector, knight).toHaveLength(CRYSTAL.featureDims.length);
    }
  });

  it('every bypass command delegates to a rune', () => {
    for (const command of CRYSTAL.bypassCommands) {
      expect(command.token.startsWith(CRYSTAL.bypassPrefix)).toBe(true);
      expect(command.delegatesRune.startsWith('//')).toBe(true);
      expect(command.knight).toBeTruthy();
    }
  });
});

describe('python <-> typescript parity', () => {
  it('reproduces every generated routing vector', () => {
    expect(CRYSTAL.vectors.length).toBeGreaterThan(0);

    for (const vector of CRYSTAL.vectors) {
      const label = `vector ${JSON.stringify(vector.input)} (tau=${vector.tau ?? 'default'})`;
      const result = routeOmniVoice(vector.input, { tau: vector.tau });

      expect(result.status, label).toBe(vector.status);
      expect(result.path, label).toBe(vector.path);
      expect(result.knight ?? null, label).toBe(vector.knight ?? null);
      expect(result.token ?? null, label).toBe(vector.token ?? null);
      expect(result.delegatesRune ?? null, label).toBe(vector.delegatesRune ?? null);

      if (vector.status !== 'ROUTED_SOFTMAX') continue;

      // Numeric parity: feature projection, logits and the distribution itself.
      expect(result.tau, label).toBe(vector.tau);
      expect(inferFeatures(vector.input), label).toEqual(vector.features);

      const outcome = softmaxDispatch(inferFeatures(vector.input), CRYSTAL.weights, vector.tau!);
      for (const knight of Object.keys(vector.logits!)) {
        expect(outcome.logits[knight], `${label} logit ${knight}`).toBeCloseTo(
          vector.logits![knight],
          EPSILON_DIGITS,
        );
        expect(outcome.probabilities[knight], `${label} P(${knight})`).toBeCloseTo(
          vector.probabilities![knight],
          EPSILON_DIGITS,
        );
      }
      expect(outcome.winner, label).toBe(vector.knight);
      expect(outcome.confidence, label).toBeCloseTo(vector.confidence!, EPSILON_DIGITS);
      expect(result.confidence!, label).toBeCloseTo(vector.confidence!, EPSILON_DIGITS);
    }
  });
});

describe('runic bypass', () => {
  it('only fires when the token opens the utterance', () => {
    expect(detectRune('ᛟ_SILENCE')).not.toBeNull();
    expect(detectRune('   ᛟ_SILENCE   ')).not.toBeNull();
    expect(detectRune('please ᛟ_SILENCE')).toBeNull();
  });

  it('tolerates ASR trailing punctuation and nothing more', () => {
    expect(detectRune('ᛟ_STATUS.')).not.toBeNull();
    expect(detectRune('ᛟ_STATUS!')).not.toBeNull();
    expect(detectRune('ᛟ_STATUSES')).toBeNull();
  });

  it('ignores undeclared and empty input', () => {
    expect(detectRune('ᛟ_NOPE')).toBeNull();
    expect(detectRune('')).toBeNull();
    expect(detectRune('   ')).toBeNull();
    expect(detectRune('just talking')).toBeNull();
  });

  it('routes ᛟ_SILENCE to the interlock knight with zero inference cost', () => {
    const result = routeOmniVoice('ᛟ_SILENCE');
    expect(result.status).toBe('ROUTED_BYPASS');
    expect(result.path).toBe('runic_bypass');
    expect(result.knight).toBe('sir_sentinel');
    expect(result.delegatesRune).toBe('//BIFROST_LOCK');
    expect(result.llmInferenceCost).toBe(0);
  });
});

describe('softmax persona dispatch', () => {
  it('tau=0 is a one-hot argmax', () => {
    const features = inferFeatures('let me speak to you');
    const outcome = softmaxDispatch(features, CRYSTAL.weights, 0);
    expect(outcome.confidence).toBe(1);
    expect(Object.values(outcome.probabilities).filter((p) => p === 1)).toHaveLength(1);
    expect(outcome.probabilities[outcome.winner]).toBe(1);
  });

  it('tau=0 is deterministic across calls', () => {
    const features = inferFeatures('forge a new audio pipeline now');
    const winners = new Set(
      Array.from({ length: 5 }, () => softmaxDispatch(features, CRYSTAL.weights, 0).winner),
    );
    expect(winners.size).toBe(1);
  });

  it('tau=1 yields a normalised distribution', () => {
    const features = inferFeatures('create a new build for the voice pipeline');
    const outcome = softmaxDispatch(features, CRYSTAL.weights, 1);
    const total = Object.values(outcome.probabilities).reduce((a, b) => a + b, 0);
    expect(total).toBeCloseTo(1, EPSILON_DIGITS);
    expect(outcome.confidence).toBeGreaterThan(0);
    expect(outcome.confidence).toBeLessThanOrEqual(1);
  });

  it('a privacy utterance never lands on the build or voice lane', () => {
    expect(routeOmniVoice('my password and private key leaked').knight).toBe('sir_sentinel');
  });
});

describe('governance gates', () => {
  it('rejects a tau outside the Sentinel policy', () => {
    expect(() => resolveTau(CRYSTAL, 7)).toThrow(TauPolicyError);
    expect(resolveTau(CRYSTAL, 0)).toBe(0);
    expect(resolveTau(CRYSTAL, 1)).toBe(1);
    expect(resolveTau(CRYSTAL)).toBe(CRYSTAL.tauPolicy.deterministicTau);
  });

  it('reports a denied tau instead of crashing the voice lane', () => {
    const result = routeOmniVoice('hello', { tau: 7 });
    expect(result.status).toBe('TAU_POLICY_DENIED');
    expect(result.error).toContain('tau');
    expect(result.knight).toBeUndefined();
  });

  it('reports a feature dimension mismatch', () => {
    const result = routeOmniVoice('hello', { features: [1, 0] });
    expect(result.status).toBe('FEATURE_DIM_MISMATCH');
  });
});
