"""MASON squire — report writer. Produces colony_report.md from all squire outputs."""
from __future__ import annotations
from datetime import datetime, timezone
from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from .index import ColonyIndex
    from .ghost import GhostReport
    from .sweep import SweepReport
    from .judge import Verdict
    from .vector import TFIDFCorpus


def _ts() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")


def build_report(
    root: Path,
    index: "ColonyIndex",
    ghost: "GhostReport",
    sweep: "SweepReport",
    verdict: "Verdict",
    out_path: Path | None = None,
) -> Path:
    out_path = out_path or (root / "colony_report.md")

    lines: list[str] = []

    lines += [
        "# CLARITY_CORE Colony Report",
        f"**Generated:** {_ts()}",
        f"**Root:** `{root}`",
        "",
        "---",
        "",
        "## Executive Summary",
        "",
        f"| Metric | Value |",
        f"|--------|-------|",
        f"| Files scanned | {index.stats.get('total_files', 0):,} |",
        f"| Total lines | {index.stats.get('total_lines', 0):,} |",
        f"| Symbols indexed | {index.stats.get('total_symbols', 0):,} |",
        f"| Risk Score | {verdict.risk_score:.1f} / 100 |",
        f"| Risk Label | **{verdict.risk_label}** |",
        f"| HITL Required | {'Yes ⚠️' if verdict.requires_hitl else 'No ✅'} |",
        "",
    ]

    # Findings
    lines += ["## Findings", ""]
    for f in verdict.findings:
        lines.append(f"- {f}")
    lines.append("")

    # Recommendations
    if verdict.recommendations:
        lines += ["## Recommendations", ""]
        for r in verdict.recommendations:
            lines.append(f"- {r}")
        lines.append("")

    # Ghost flags
    ghost_summary = ghost.summary()
    lines += [
        "## GHOST Triage",
        "",
        f"| Category | Count |",
        f"|----------|-------|",
        f"| Secrets (critical) | {ghost_summary.get('critical', 0)} |",
        f"| Warnings | {ghost_summary.get('warnings', 0)} |",
        f"| Info | {ghost_summary.get('info', 0)} |",
        "",
    ]
    criticals = ghost.critical
    if criticals:
        lines.append("### Critical Flags")
        lines.append("")
        for flag in criticals[:20]:
            lines.append(f"- `{flag.file}:{flag.line}` — {flag.kind}: {flag.detail}")
        if len(criticals) > 20:
            lines.append(f"- ... and {len(criticals) - 20} more")
        lines.append("")

    # Sweep flags
    sw_summary = sweep.summary()
    lines += [
        "## SWEEP Report",
        "",
        f"| Category | Count |",
        f"|----------|-------|",
    ]
    for k, v in sw_summary.items():
        if k != "total":
            lines.append(f"| {k.replace('_', ' ').title()} | {v} |")
    lines.append("")

    # Index stats
    by_ext = index.stats.get("by_ext", {})
    if by_ext:
        lines += ["## Language Breakdown", ""]
        lines += ["| Extension | Files |", "|-----------|-------|"]
        for ext, cnt in sorted(by_ext.items(), key=lambda x: -x[1])[:15]:
            lines.append(f"| `{ext}` | {cnt} |")
        lines.append("")

    # Top symbols
    if index.symbols:
        lines += ["## Symbol Index (Top 30)", ""]
        lines += ["| Symbol | Kind | File | Line |", "|--------|------|------|------|"]
        for sym in index.symbols[:30]:
            lines.append(f"| `{sym.name}` | {sym.kind} | `{sym.file}` | {sym.line_hint} |")
        if len(index.symbols) > 30:
            lines.append(f"\n*...and {len(index.symbols) - 30} more symbols in full index.*")
        lines.append("")

    lines += [
        "---",
        "",
        "*Generated by CLARITY_CORE v1.0.0 — Squire Colony*",
        "*Pipeline: SCAN → INDEX → GHOST → SWEEP → JUDGE → SENTINEL → MASON*",
    ]

    out_path.write_text("\n".join(lines), encoding="utf-8")
    return out_path
