// SPDX-License-Identifier: MIT
/**
 * T3Code Scaffold Compiler — Full-stack agentic generation helper.
 * Generates type-safe Next.js + Tailwind v4 + tRPC component scaffolding.
 */

export interface T3ComponentOptions {
  name: string;
  route: string;
  withTRPC?: boolean;
}

export function generateT3Scaffold(options: T3ComponentOptions): string {
  const { name, route, withTRPC = true } = options;
  return `// Generated by t3code compiler for route: ${route}
'use client';

import React from 'react';
${withTRPC ? `// import { trpc } from '../lib/trpc';\n` : ''}
export function ${name}() {
  return (
    <div className="border border-gold/30 bg-obsidian p-5 font-mono text-white">
      <h2 className="text-sm font-display uppercase tracking-widest text-gold-royal">${name}</h2>
      <p className="mt-2 text-xs text-white/60">T3-Stack Scaffolding active on route: ${route}</p>
    </div>
  );
}
`;
}
