# Copyright (c) 2026 Invisioned Marketing Inc. All rights reserved.
# Camelot Apex OS — CONFIDENTIAL AND PROPRIETARY
"""
Cribo Bundler: The Kinetic Python Module Linker
Bundles Python packages into single standalone .py files for zero-dependency deployment.
"""

import ast
import hashlib
import sys
from pathlib import Path
from typing import Dict, List, Set


class CriboBundler:
    """
    Cribo (Latin: "To Sift")
    Bundles Python code by sifting through imports and inlining dependencies.
    """

    def __init__(self, entry_point: str, output_path: str = None, search_paths: List[str] = None):
        self.entry_point = Path(entry_point).resolve()
        if not self.entry_point.exists():
            raise FileNotFoundError(f"Entry point {self.entry_point} not found")

        self.project_root = self.entry_point.parent
        self.output_path = (
            Path(output_path) if output_path else self.entry_point.parent / f"{self.entry_point.stem}_bundled.py"
        )

        # Enhanced Search Paths
        self.search_paths = [self.project_root]
        if search_paths:
            self.search_paths.extend([Path(p).resolve() for p in search_paths])

        # Auto-detect common roots
        repo_root = self.project_root.parent
        self.search_paths.append(repo_root)  # CAMELOT_OS
        self.search_paths.append(repo_root / "src")  # CAMELOT_OS/src

        self.processed_files: Set[Path] = set()
        self.module_registry: Dict[str, str] = {}  # module_name -> code
        self.stdlib_modules = self._get_stdlib_modules()

    def _get_stdlib_modules(self) -> Set[str]:
        """Get set of standard library module names"""
        return set(sys.builtin_module_names) | set(sys.modules.keys())

    def analyze_imports(self, file_path: Path) -> List[str]:
        """
        Extract local imports from a Python file.
        Returns list of absolute paths to imported local modules.
        """
        with open(file_path, "r", encoding="utf-8") as f:
            try:
                tree = ast.parse(f.read())
            except SyntaxError:
                return []

        local_modules = []

        for node in ast.walk(tree):
            if isinstance(node, ast.Import):
                for alias in node.names:
                    self._check_local_import(alias.name, local_modules)
            elif isinstance(node, ast.ImportFrom):
                if node.module:
                    self._check_local_import(node.module, local_modules)

        return local_modules

    def _is_within_search_paths(self, resolved: Path) -> bool:
        """Reject any path that escapes all declared search roots."""
        return any(
            str(resolved).startswith(str(p.resolve()))
            for p in self.search_paths
        )

    def _check_local_import(self, module_name: str, local_modules: List[str]):
        """Check if import is local and add to list"""
        if module_name in self.stdlib_modules:
            return

        for path in self.search_paths:
            # Check for .py file
            module_path = (path / f"{module_name.replace('.', '/')}.py").resolve()
            if module_path.exists() and self._is_within_search_paths(module_path):
                local_modules.append(module_path)
                return

            # Check for package (__init__.py)
            package_path = (path / module_name.replace(".", "/") / "__init__.py").resolve()
            if package_path.exists() and self._is_within_search_paths(package_path):
                local_modules.append(package_path)
                return

    def bundle(self):
        """
        Execute the bundling process.
        """
        print(f"📦 [Cribo] Bundling {self.entry_point.name}...")

        # 1. Recursive analysis
        files_to_process = [self.entry_point]
        main_code = ""

        while files_to_process:
            current_file = files_to_process.pop(0)
            if current_file in self.processed_files:
                continue

            self.processed_files.add(current_file)

            # Read code
            with open(current_file, "r", encoding="utf-8") as f:
                code = f.read()

            if current_file == self.entry_point:
                main_code = code
            else:
                # Store module code in registry
                module_name = current_file.stem
                if current_file.name == "__init__.py":
                    module_name = current_file.parent.name
                self.module_registry[module_name] = code

            # Find dependencies
            deps = self.analyze_imports(current_file)
            files_to_process.extend(deps)

        # 2. Construct bundle
        bundled_content = [
            f"# 🏗️ CRIBO BUNDLE: {self.entry_point.name}",
            "# Generated by Camelot OS Cribo Bundler",
            "# ------------------------------------------------",
            "import sys",
            "from types import ModuleType",
            "",
            "# --- BUNDLED MODULES ---",
            "",
        ]

        # In-memory module loader shim
        bundled_content.append(
            """
import hashlib as _hashlib

class CriboLoader:
    def __init__(self, registry, hashes):
        self.registry = registry
        self._hashes = hashes

    def find_module(self, fullname, path=None):
        if fullname in self.registry:
            return self
        return None

    def load_module(self, fullname):
        if fullname in sys.modules:
            return sys.modules[fullname]
        code = self.registry[fullname]
        expected = self._hashes.get(fullname, "")
        actual = _hashlib.sha256(code.encode()).hexdigest()
        if actual != expected:
            raise ImportError(
                f"[Cribo] Integrity check failed for '{fullname}': "
                f"bundle may have been tampered with"
            )
        module = ModuleType(fullname)
        sys.modules[fullname] = module
        exec(compile(code, fullname, "exec"), module.__dict__)
        return module

# Registry of bundled code
_cribo_registry = {}
_cribo_hashes = {}
"""
        )

        # Add modules to registry with SHA-256 integrity hashes
        for name, code in self.module_registry.items():
            safe_code = code.replace('"""', '\\"\\"\\"')
            code_hash = hashlib.sha256(code.encode()).hexdigest()
            bundled_content.append(f'_cribo_registry["{name}"] = """{safe_code}"""')
            bundled_content.append(f'_cribo_hashes["{name}"] = "{code_hash}"')

        # Register loader with both registry and hash manifest
        bundled_content.append(
            """
sys.meta_path.append(CriboLoader(_cribo_registry, _cribo_hashes))
"""
        )

        # Add main entry point code
        bundled_content.append("# --- MAIN ENTRY POINT ---")
        bundled_content.append(main_code)

        # 3. Write output
        with open(self.output_path, "w", encoding="utf-8") as f:
            f.write("\n".join(bundled_content))

        print(f"✅ [Cribo] Bundle created at: {self.output_path}")
        print(f"   - Modules packed: {len(self.module_registry)}")
        print(f"   - Total size: {self.output_path.stat().st_size} bytes")


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python cribo.py <entry_point.py> [output.py]")
        sys.exit(1)

    entry = sys.argv[1]
    out = sys.argv[2] if len(sys.argv) > 2 else None

    bundler = CriboBundler(entry, out)
    bundler.bundle()