# Copyright (c) 2026 Invisioned Marketing Inc. All rights reserved.
# Camelot Apex OS — CONFIDENTIAL AND PROPRIETARY
"""
HERMES_PRIME PHIAL: Sovereign MetaCompiler Forage Engine
==========================================================
Executable PhialEngine for HERMES_PRIME_NEXUS — the Monitor-Generate-Verify
(MGV) research loop with Ouroboros memory and Phial weight re-weighting.

Blueprint hooks (Knights/Hermes_Prime/*):
  spark.md   -> MGV framework, Ouroboros Memory, AlphaEvolve self-correction
  skills.md  -> symbolect triggers 🧲[FORAGE] 🧪[TEST] 📈[EVOLVE] 🏆[DEPLOY]
  harness.md -> runic_router bindings (//SYNC_VFS_WORKSPACE,
                //FORGE_HERMES_PRIME_FILES, //IGNITE_SELF_EVOLUTION_LOOP)

Integration:
  - control_plane/runes/runic_router.py lazy-loads this module (importlib)
  - state persists to 03_VAULT/runtime_state/hermes_prime_phial.json
  - self-test: python 01_KERNEL/titan/phials/hermes_prime_phial.py --test

CLI:
  --cycle "<seed>"   run one full MGV cycle
  --forge            idempotently scaffold Knights/Hermes_Prime VFS files
  --sync             report VFS state
  --state            dump engine state (weights + memory + stats)
  --deploy "<seed>"  deploy a verified research artifact (νKG-style crystal)
  --reset            reset weights/memory/stats
  --test             run the built-in self-check
"""

from __future__ import annotations

import json
import os
import re
import subprocess
import sys
import threading
import time
import uuid
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional

_CAMELOT_ROOT = Path(__file__).resolve().parents[3]
_VFS_REL = "Knights/Hermes_Prime"
_SCAFFOLD_FILES = ("soul.md", "spark.md", "harness.md", "skills.md", "merlin_notebook_blend.md")
_DEFAULT_STATE_PATH = _CAMELOT_ROOT / "03_VAULT" / "runtime_state" / "hermes_prime_phial.json"

# Ouroboros / AlphaEvolve tuning
_MAX_MEMORY = 50            # cycle records kept in the memory bank
_LR = 0.10                  # adaptive weight learning rate
_BLACKLIST_THRESHOLD = 1.0  # penalty at which a known-bad target is skipped
_MAX_HYPOTHESES = 8

# Modules considered safe to probe as import checks without executing them.
_SAFE_IMPORTS = {
    "os", "sys", "json", "re", "subprocess", "threading", "time", "uuid",
    "datetime", "pathlib", "importlib", "typing", "dataclasses", "collections",
}
# Read-only command allowlist — the ONLY commands the engine may run.
# NOTE: only side-effect-free commands are allowed (no rune routing: routing
# would append to the production harness queue).
_SAFE_COMMANDS: Dict[str, List[str]] = {
    "router_list": [sys.executable, "-m", "control_plane.runes.runic_router", "--list"],
}
_SKIP_TOKENS = {
    "import", "from", "the", "a", "an", "and", "or", "to", "of", "for", "in",
    "with", "on", "at", "verify", "check", "run", "build", "deploy", "sync",
    "forage", "research", "cycle", "seed", "loop", "vfs", "file", "module",
}

_DEFAULT_WEIGHTS: Dict[str, float] = {
    "forage_breadth": 0.60,     # how widely Monitor scans for signals
    "hypothesis_count": 0.50,   # research vector density
    "verify_strictness": 0.50,  # pass threshold shaping
    "deploy_threshold": 0.70,   # pass_ratio needed to 🏆[DEPLOY]
    "ouroboros_decay": 0.90,    # per-cycle decay of known-bad penalties
}


def _clamp(v: float, lo: float = 0.0, hi: float = 1.0) -> float:
    return max(lo, min(hi, v))


class Hypothesis:
    """A single verifiable research assertion (research vector)."""

    __slots__ = ("kind", "target", "label")

    def __init__(self, kind: str, target: str, label: str):
        self.kind = kind          # "path_exists" | "imports" | "probe" | "command"
        self.target = target
        self.label = label

    def to_dict(self) -> Dict[str, Any]:
        return {"kind": self.kind, "target": self.target, "label": self.label}


class Outcome:
    """Verification result for one hypothesis."""

    __slots__ = ("hypothesis", "passed", "detail")

    def __init__(self, hypothesis: Hypothesis, passed: bool, detail: str):
        self.hypothesis = hypothesis
        self.passed = passed
        self.detail = detail


def _stub(name: str) -> str:
    """Minimal stub written only when a scaffold file is missing."""
    return (
        f"# {name} (auto-generated by Hermes_Prime PhialEngine — {time.strftime('%Y-%m-%d')})\n"
        "# Canonical content lives in Knights/Hermes_Prime/ — run "
        "#   python 01_KERNEL/titan/phials/hermes_prime_phial.py --forge\n"
        "# to reconcile this scaffold with the blueprint protocol.\n"
    )


class PhialEngine:
    """Sovereign MetaCompiler Forage Engine (MGV + Ouroboros + re-weighting)."""

    def __init__(self, state_path: Optional[Path] = None, base_dir: Optional[Path] = None):
        self.base_dir = Path(base_dir) if base_dir else _CAMELOT_ROOT
        self.vfs_dir = self.base_dir / _VFS_REL
        self.state_path = Path(state_path) if state_path else _DEFAULT_STATE_PATH
        self._lock = threading.RLock()

        self.weights: Dict[str, float] = dict(_DEFAULT_WEIGHTS)
        self.memory: List[Dict[str, Any]] = []      # Ouroboros bank (cycle records)
        self.blacklist: Dict[str, float] = {}       # known-bad target -> penalty
        self.stats: Dict[str, Any] = {
            "cycles_run": 0,
            "hypotheses_verified": 0,
            "pass_total": 0,
            "fail_total": 0,
            "artifacts_deployed": 0,
            "last_cycle_id": None,
            "created": datetime.now(timezone.utc).isoformat(),
        }
        self._load()

    # ------------------------------------------------------------------ state
    def _load(self) -> None:
        try:
            if self.state_path.exists():
                raw = json.loads(self.state_path.read_text(encoding="utf-8"))
                self.weights = {**self.weights, **raw.get("weights", {})}
                self.memory = raw.get("memory", [])[-_MAX_MEMORY:]
                self.blacklist = {k: float(v) for k, v in raw.get("blacklist", {}).items()}
                self.stats = {**self.stats, **raw.get("stats", {})}
        except (OSError, json.JSONDecodeError, ValueError):
            pass  # corrupt/missing state -> start fresh

    def _save(self) -> None:
        self.state_path.parent.mkdir(parents=True, exist_ok=True)
        payload = {
            "schema": "camelot-os.phial/hermes_prime/v1",
            "weights": self.weights,
            "memory": self.memory[-_MAX_MEMORY:],
            "blacklist": self.blacklist,
            "stats": self.stats,
            "updated": datetime.now(timezone.utc).isoformat(),
        }
        tmp = self.state_path.with_suffix(".json.tmp")
        tmp.write_text(json.dumps(payload, indent=2, ensure_ascii=False), encoding="utf-8")
        os.replace(tmp, self.state_path)  # atomic

    def state(self) -> Dict[str, Any]:
        with self._lock:
            return {
                "weights": dict(self.weights),
                "blacklist": {k: round(v, 3) for k, v in self.blacklist.items()},
                "memory_records": len(self.memory),
                "last_cycle": self.memory[-1] if self.memory else None,
                "stats": dict(self.stats),
                "state_path": str(self.state_path),
                "vfs_dir": str(self.vfs_dir),
            }

    def reset(self) -> Dict[str, Any]:
        with self._lock:
            self.weights = dict(_DEFAULT_WEIGHTS)
            self.memory = []
            self.blacklist = {}
            self.stats = {
                "cycles_run": 0, "hypotheses_verified": 0, "pass_total": 0,
                "fail_total": 0, "artifacts_deployed": 0, "last_cycle_id": None,
                "created": self.stats.get("created"),
            }
            self._save()
            return {"status": "RESET", "state": self.state()}

    # ------------------------------------------------------------- MONITOR 🧲
    def monitor(self, seed: str) -> List[Dict[str, Any]]:
        """Forage real state: VFS scaffold, pending queue signals, memory."""
        signals: List[Dict[str, Any]] = []

        # 1. VFS scaffold integrity
        for name in _SCAFFOLD_FILES:
            p = self.vfs_dir / name
            signals.append({"source": "vfs", "kind": "path_exists", "target": str(p), "present": p.exists()})

        # 2. Harness queue mentions (read-only)
        try:
            queue = self.base_dir / "logs" / "harness_queue.jsonl"
            if queue.exists():
                lines = queue.read_text(encoding="utf-8", errors="ignore").splitlines()[-20:]
                for line in lines:
                    if re.search(r"hermes_prime|Hermes_Prime", line, re.IGNORECASE):
                        signals.append({"source": "queue", "kind": "signal", "target": line[:120]})
        except OSError:
            pass

        # 3. Ouroboros: tail feeds the head — recent failures re-enter the loop
        for rec in self.memory[-5:]:
            for t in rec.get("failed_targets", [])[:3]:
                signals.append({
                    "source": "ouroboros", "kind": "known_bad", "target": t,
                    "penalty": round(self.blacklist.get(t, 0.0), 3),
                })

        # 4. Seed tokens as direct forage targets
        for tok in self._tokens(seed):
            signals.append({"source": "seed", "kind": "target", "target": tok})

        return signals

    # ----------------------------------------------------------- GENERATE 🧪
    @staticmethod
    def _tokens(seed: str) -> List[str]:
        out: List[str] = []
        for tok in seed.split():
            tok = tok.strip(".,;:()[]{}\"'`")
            if not tok or tok.lower() in _SKIP_TOKENS:
                continue
            if re.fullmatch(r"[A-Za-z_][\w.]*", tok) or re.search(r"[\\/]", tok) or tok.startswith("cmd:"):
                out.append(tok)
        return out

    def generate(self, seed: str, signals: List[Dict[str, Any]]) -> List[Hypothesis]:
        # Seed-derived research vectors FIRST — explicit targets are always
        # honored; the Phial hypothesis cap only trims baseline filler below.
        hyps: List[Hypothesis] = []
        for tok in self._tokens(seed):
            if tok.startswith("cmd:"):
                key = tok[4:]
                if key in _SAFE_COMMANDS:
                    hyps.append(Hypothesis("command", key, f"command:{key}"))
                continue
            if re.search(r"[\\/]", tok):
                target = tok if os.path.isabs(tok) else str(self.base_dir / tok)
                hyps.append(Hypothesis("path_exists", target, f"path:{tok}"))
                continue
            if "." in tok:
                hyps.append(Hypothesis("imports", tok, f"module:{tok}"))
            elif tok in _SAFE_IMPORTS:
                hyps.append(Hypothesis("imports", tok, f"module:{tok}"))
            else:
                hyps.append(Hypothesis("probe", tok, f"probe:{tok}"))

        # Hypothesis cap from Phial weight (density control) — bounds both
        # the forage loop below and baseline filler trimming.
        cap = max(2, min(_MAX_HYPOTHESES, int(2 + self.weights["hypothesis_count"] * 8)))

        # Domain routing from signals (only when explicitly seeded)
        if re.search(r"forage|research|nexus", seed, re.IGNORECASE):
            hyps.append(Hypothesis("imports", "control_plane.runes.runic_router", "domain:router"))
            # Monitor → Generate: forage queue signals as probe vectors (bounded
            # by the Phial cap so the loop cannot balloon).
            for sig in signals:
                if sig.get("source") == "queue" and len(hyps) < cap:
                    text = str(sig.get("target", ""))[:60]
                    if text:
                        hyps.append(Hypothesis("probe", text, "queue:foraged"))

        # Baseline filler (VFS scaffold integrity + engine self-check).
        # Ouroboros: known-bad baseline targets are skipped while their penalty
        # exceeds the threshold — the tail feeds the head.
        baseline: List[Hypothesis] = [Hypothesis("imports", "os", "engine:self_check")]
        for name in _SCAFFOLD_FILES:
            target = str(self.vfs_dir / name)
            if self.blacklist.get(target, 0.0) <= _BLACKLIST_THRESHOLD:
                baseline.append(Hypothesis("path_exists", target, f"scaffold:{name}"))

        room = max(0, cap - len(hyps))
        return hyps + baseline[:room]

    # ------------------------------------------------------------- VERIFY 🧪
    @staticmethod
    def _check_import(name: str) -> bool:
        try:
            __import__(name)
            return True
        except ImportError:
            # dotted path may be a repo-local module — probe the file layout
            try:
                import importlib.util

                top = name.split(".")[0]
                p = _CAMELOT_ROOT / (name.replace(".", "/") + ".py")
                if p.exists():
                    spec = importlib.util.spec_from_file_location(name, p)
                    return spec is not None and spec.loader is not None
                return top in sys.modules
            except Exception:
                return False

    @staticmethod
    def _run_safe_command(key: str) -> bool:
        cmd = _SAFE_COMMANDS.get(key)
        if not cmd:
            return False
        try:
            res = subprocess.run(
                cmd, capture_output=True, timeout=20, cwd=str(_CAMELOT_ROOT),
            )
            return res.returncode == 0
        except (subprocess.TimeoutExpired, OSError):
            return False

    def verify(self, hyps: List[Hypothesis]) -> List[Outcome]:
        corpus: List[str] = []
        for name in _SCAFFOLD_FILES:
            p = self.vfs_dir / name
            if p.exists():
                try:
                    corpus.append(p.read_text(encoding="utf-8", errors="ignore"))
                except OSError:
                    pass
        try:
            corpus.append(Path(__file__).read_text(encoding="utf-8", errors="ignore"))
        except OSError:
            pass
        corpus_text = "\n".join(corpus).lower()

        outcomes: List[Outcome] = []
        for h in hyps:
            try:
                if h.kind == "path_exists":
                    passed = os.path.exists(h.target)
                    detail = "exists" if passed else "missing"
                elif h.kind == "imports":
                    passed = self._check_import(h.target)
                    detail = "importable" if passed else "not importable"
                elif h.kind == "command":
                    passed = self._run_safe_command(h.target)
                    detail = "exit=0" if passed else "exit!=0"
                elif h.kind == "probe":
                    passed = h.target.lower() in corpus_text
                    detail = "found in corpus" if passed else "absent from corpus"
                else:
                    passed, detail = False, "unknown_kind"
            except Exception as e:  # verify never raises — strictness lives in data
                passed, detail = False, str(e)
            outcomes.append(Outcome(h, passed, detail))
        return outcomes

    # ------------------------------------------------------------- EVOLVE 📈
    def evolve(self, outcomes: List[Outcome], seed: str) -> Dict[str, Any]:
        total = len(outcomes) or 1
        passed = sum(1 for o in outcomes if o.passed)
        ratio = passed / total

        # Ouroboros: decay every penalty, then reinforce failures
        for k in list(self.blacklist):
            self.blacklist[k] *= self.weights["ouroboros_decay"]
            if self.blacklist[k] < 0.05:
                del self.blacklist[k]
        failed_targets: List[str] = []
        for o in outcomes:
            if not o.passed:
                self.blacklist[o.hypothesis.target] = self.blacklist.get(o.hypothesis.target, 0.0) + 1.0
                failed_targets.append(o.hypothesis.target)

        # AlphaEvolve: adaptive weight re-weighting from cycle yield
        w = self.weights
        w["forage_breadth"] = _clamp(w["forage_breadth"] + _LR * (ratio - 0.5))
        w["hypothesis_count"] = _clamp(w["hypothesis_count"] + _LR * (ratio - 0.5))
        w["verify_strictness"] = _clamp(w["verify_strictness"] + _LR * (0.5 - ratio))
        w["deploy_threshold"] = _clamp(w["deploy_threshold"] + _LR * (ratio - 0.5))

        if ratio >= w["deploy_threshold"]:
            verdict = "DEPLOY"
        elif ratio >= 0.4:
            verdict = "REVISE"
        else:
            verdict = "ABORT"

        return {
            "passed": passed, "failed": total - passed, "pass_ratio": round(ratio, 3),
            "verdict": verdict, "failed_targets": failed_targets,
        }

    # ------------------------------------------------------------- CYCLE ⚡
    def run_cycle(self, seed: str = "default research cycle") -> Dict[str, Any]:
        with self._lock:
            signals = self.monitor(seed)
            hyps = self.generate(seed, signals)
            outcomes = self.verify(hyps)
            weights_before = dict(self.weights)
            evolve = self.evolve(outcomes, seed)

            cycle_id = f"hp-{uuid.uuid4().hex[:8]}"
            self.stats["cycles_run"] = int(self.stats.get("cycles_run", 0)) + 1
            self.stats["hypotheses_verified"] = int(self.stats.get("hypotheses_verified", 0)) + len(outcomes)
            self.stats["pass_total"] = int(self.stats.get("pass_total", 0)) + evolve["passed"]
            self.stats["fail_total"] = int(self.stats.get("fail_total", 0)) + evolve["failed"]
            self.stats["last_cycle_id"] = cycle_id

            record = {
                "cycle_id": cycle_id,
                "seed": seed,
                "ts": datetime.now(timezone.utc).isoformat(),
                "signals": len(signals),
                "hypotheses": [h.to_dict() for h in hyps],
                "passed": evolve["passed"],
                "failed": evolve["failed"],
                "verdict": evolve["verdict"],
                "failed_targets": evolve["failed_targets"],
            }
            self.memory.append(record)
            self.memory = self.memory[-_MAX_MEMORY:]
            self._save()

            return {
                "cycle_id": cycle_id,
                "seed": seed,
                "signals": len(signals),
                "hypotheses": [h.to_dict() for h in hyps],
                "passed": evolve["passed"],
                "failed": evolve["failed"],
                "pass_ratio": evolve["pass_ratio"],
                "verdict": evolve["verdict"],
                "weights_before": weights_before,
                "weights_after": dict(self.weights),
                "blacklist": {k: round(v, 3) for k, v in self.blacklist.items()},
                "status": "CYCLE_COMPLETE",
            }

    # ---------------------------------------------------------- FORGE / SYNC
    def forge_scaffold(self) -> Dict[str, Any]:
        with self._lock:
            self.vfs_dir.mkdir(parents=True, exist_ok=True)
            created: List[str] = []
            present: List[str] = []
            for name in _SCAFFOLD_FILES:
                p = self.vfs_dir / name
                if p.exists():
                    present.append(name)
                else:
                    p.write_text(_stub(name), encoding="utf-8")
                    created.append(name)
            return {
                "action": "forge",
                "created": created,
                "present": present,
                "vfs_dir": str(self.vfs_dir),
                "status": "SCAFFOLDED" if created else "OK",
            }

    def sync_vfs(self) -> Dict[str, Any]:
        with self._lock:
            files: List[Dict[str, Any]] = []
            if self.vfs_dir.exists():
                for p in sorted(self.vfs_dir.glob("*")):
                    if p.is_file():
                        st = p.stat()
                        files.append({
                            "name": p.name,
                            "bytes": st.st_size,
                            "mtime": datetime.fromtimestamp(st.st_mtime, tz=timezone.utc).isoformat(),
                        })
            scaffold_present = [n for n in _SCAFFOLD_FILES if (self.vfs_dir / n).exists()]
            missing = [n for n in _SCAFFOLD_FILES if n not in scaffold_present]
            return {
                "action": "sync",
                "files": files,
                "scaffold_present": scaffold_present,
                "missing": missing,
                "status": "SYNCED",
            }

    # ------------------------------------------------------------ DEPLOY 🏆
    def deploy_artifact(self, seed: str) -> Dict[str, Any]:
        with self._lock:
            deploy_dir = self.base_dir / "03_VAULT" / "runtime_state" / "hermes_prime_deployments"
            deploy_dir.mkdir(parents=True, exist_ok=True)
            name = f"hermes_prime_deployed_{datetime.now(timezone.utc).strftime('%Y%m%dT%H%M%SZ')}.json"
            artifact = {
                "schema": "camelot-os.system/schema/ukg/v1/hermes_prime_artifact",
                "fingerprint": "νKG_CRYSTAL_OMEGA_STANDARDIZED",
                "knight": "HERMES_PRIME",
                "seed": seed,
                "weights": dict(self.weights),
                "deployed_at": datetime.now(timezone.utc).isoformat(),
            }
            path = deploy_dir / name
            path.write_text(json.dumps(artifact, indent=2, ensure_ascii=False), encoding="utf-8")
            self.stats["artifacts_deployed"] = int(self.stats.get("artifacts_deployed", 0)) + 1
            self._save()
            return {"action": "deploy", "artifact": str(path), "status": "DEPLOYED"}


# ------------------------------------------------------------------ singleton
_ENGINE_SINGLETON: Optional[PhialEngine] = None


def get_phial_engine() -> PhialEngine:
    global _ENGINE_SINGLETON
    if _ENGINE_SINGLETON is None:
        _ENGINE_SINGLETON = PhialEngine()
    return _ENGINE_SINGLETON


# -------------------------------------------------------------- phial_main
def phial_main(raw_input: str) -> dict:
    """Standard Phial entrypoint — JSON in {action, seed}, dict out."""
    try:
        payload = json.loads(raw_input) if raw_input.strip().startswith("{") else {"action": "cycle", "seed": raw_input}
    except json.JSONDecodeError:
        payload = {"action": "cycle", "seed": raw_input}
    action = str(payload.get("action", "cycle")).lower()
    seed = str(payload.get("seed", "default research cycle"))
    engine = PhialEngine()
    try:
        if action == "forge":
            return engine.forge_scaffold()
        if action == "sync":
            return engine.sync_vfs()
        if action == "state":
            return {"status": "OK", "state": engine.state()}
        if action == "reset":
            return engine.reset()
        if action == "deploy":
            return engine.deploy_artifact(seed)
        return engine.run_cycle(seed)  # cycle (default)
    except Exception as e:
        return {"status": "ERROR", "action": action, "message": str(e)}


def _self_test() -> int:
    """Side-effect-free self-check: runs entirely in a temp workspace."""
    import tempfile

    ok = True

    def check(name: str, cond: bool, detail: str = "") -> None:
        nonlocal ok
        mark = "PASS" if cond else "FAIL"
        if not cond:
            ok = False
        print(f"[{mark}] {name} {detail}")

    with tempfile.TemporaryDirectory() as td:
        base = Path(td)
        engine = PhialEngine(state_path=base / "state.json", base_dir=base)
        check("engine loads", isinstance(engine, PhialEngine))
        check("default weights", abs(engine.weights["deploy_threshold"] - 0.70) < 1e-9)

        sync = engine.sync_vfs()
        check("sync_vfs structured", sync["status"] == "SYNCED", f"({len(sync['files'])} files)")

        cycle = engine.run_cycle("forage os and check the nexus scaffold")
        check("MGV cycle completes", cycle["status"] == "CYCLE_COMPLETE", f"(verdict={cycle['verdict']}, ratio={cycle['pass_ratio']})")
        check("cycle structured", all(k in cycle for k in ("passed", "failed", "weights_after", "blacklist")))

        state = engine.state()
        check("state persisted", engine.state_path.exists(), f"({engine.state_path.name})")
        check("memory bank fed", state["memory_records"] >= 1)

        first = engine.forge_scaffold()
        second = engine.forge_scaffold()
        check("forge idempotent", first["status"] == "SCAFFOLDED" and second["status"] == "OK" and not second["created"])

        deploy = engine.deploy_artifact("verified research artifact")
        check("deploy writes artifact", deploy["status"] == "DEPLOYED" and Path(deploy["artifact"]).exists())

    print("\nHermes_Prime PhialEngine self-test:", "ALL PASS" if ok else "FAILURES PRESENT")
    return 0 if ok else 1


if __name__ == "__main__":
    import argparse

    ap = argparse.ArgumentParser(prog="hermes_prime_phial", description="Hermes_Prime PhialEngine (MGV + Ouroboros + re-weighting)")
    ap.add_argument("--cycle", metavar="SEED", help="run one MGV cycle")
    ap.add_argument("--forge", action="store_true", help="scaffold VFS files")
    ap.add_argument("--sync", action="store_true", help="report VFS state")
    ap.add_argument("--state", action="store_true", help="dump engine state")
    ap.add_argument("--deploy", metavar="SEED", help="deploy a verified artifact")
    ap.add_argument("--reset", action="store_true", help="reset engine state")
    ap.add_argument("--test", action="store_true", help="run built-in self-check")
    args = ap.parse_args()

    try:
        sys.stdout.reconfigure(encoding="utf-8")
    except (AttributeError, ValueError):
        pass

    if args.test:
        sys.exit(_self_test())

    engine = PhialEngine()
    if args.forge:
        print(json.dumps(engine.forge_scaffold(), indent=2, ensure_ascii=False))
    elif args.sync:
        print(json.dumps(engine.sync_vfs(), indent=2, ensure_ascii=False))
    elif args.state:
        print(json.dumps(engine.state(), indent=2, ensure_ascii=False))
    elif args.reset:
        print(json.dumps(engine.reset(), indent=2, ensure_ascii=False))
    elif args.deploy is not None:
        print(json.dumps(engine.deploy_artifact(args.deploy), indent=2, ensure_ascii=False))
    else:
        seed = args.cycle if args.cycle is not None else "default research cycle"
        print(json.dumps(engine.run_cycle(seed), indent=2, ensure_ascii=False))
