server {
    listen 8080;
    server_name _;
    root /usr/share/nginx/html;

    location = / {
        return 302 /kickbox/;
    }
    location /kickbox/ {
        index index.html;
    }
    location /contracts/ {
        types { }
        default_type application/javascript;
    }
}
