#!/usr/bin/env bash
# SPDX-License-Identifier: MIT
#
# Deploy a private ntfy alert server on the Camelot hub.
#
# Installs to /usr/local/{bin,etc} (outside both git checkouts, per the
# deploy-hub-selfcheck staleness rule), binds the tailscale0 address only,
# enforces deny-all auth, and writes a least-privilege access token into the
# alert unit's drop-in (root-only file, never echoed).
#
# Users:
#   admin  - management plane (created from CAMELOT_NTFY_ADMIN_PASSWORD)
#   alerts - the publisher the alert unit runs as; role=user, write-only on
#            the topic. ACLs do not apply to admins, so the publisher must
#            not be the admin (least privilege).
#
# Idempotent: re-runs preserve the user database and previously issued tokens.
# Requires CAMELOT_NTFY_ADMIN_PASSWORD in the environment on first run
# (delivered to the hub via stdin, never argv).
#
# ntfy >= 2.28 CLI notes: per-command --config was removed; the config file is
# selected via the NTFY_CONFIG_FILE environment variable, and the auth DB is
# created by the server on first start - hence start-before-provision order.
#
# Usage:
#   CAMELOT_NTFY_ADMIN_PASSWORD=... bash scripts/ops/deploy-hub-ntfy.sh
#   CAMELOT_HUB=user@host CAMELOT_NTFY_ADMIN_PASSWORD=... bash scripts/ops/deploy-hub-ntfy.sh

set -euo pipefail

HUB="${CAMELOT_HUB:-root@162.35.107.134}"
NTFY_VERSION="${NTFY_VERSION:-2.28.0}"
CONF=/etc/camelot/ntfy
PORT="${CAMELOT_NTFY_PORT:-25871}"
TOPIC="${CAMELOT_NTFY_TOPIC:-camelot-alerts}"

SSH=(ssh -o BatchMode=yes -o ConnectTimeout=15 "$HUB")
SCP=(scp -o BatchMode=yes -o ConnectTimeout=15)

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"

say() { printf '\n\033[1m%s\033[0m\n' "$1"; }

say "1) fetch tailscale address + preflight"
TS_IP="$("${SSH[@]}" "ip -4 -o addr show tailscale0 2>/dev/null | awk '{print \$4}' | cut -d/ -f1 | head -1")"
if [[ -z "$TS_IP" ]]; then
  echo "  FATAL: no tailscale0 address on the hub" >&2
  exit 1
fi
echo "  tailscale bind acquired (address not echoed)"

say "2) install ntfy binary $NTFY_VERSION (skipped if present)"
"${SSH[@]}" "set -e; if [ -x /usr/local/bin/ntfy ]; then
    echo '  already installed'
  else
    curl -sSfL -o /tmp/ntfy.tgz https://github.com/binwiederhier/ntfy/releases/download/v${NTFY_VERSION}/ntfy_${NTFY_VERSION}_linux_amd64.tar.gz
    tar -xzf /tmp/ntfy.tgz -C /tmp ntfy_${NTFY_VERSION}_linux_amd64/ntfy
    install -m 0755 /tmp/ntfy_${NTFY_VERSION}_linux_amd64/ntfy /usr/local/bin/ntfy
    rm -rf /tmp/ntfy.tgz /tmp/ntfy_${NTFY_VERSION}_linux_amd64
    echo '  installed'
  fi"

say "3) write config (deny-all auth, tailscale-only bind)"
"${SSH[@]}" "set -e; mkdir -p '$CONF' && chmod 0750 '$CONF' && cat > $CONF/server.yml <<EOF
# Generated by scripts/ops/deploy-hub-ntfy.sh. Private alert bus: no public
# plane, no anonymous access, tailscale-only bind.
base-url: \"http://$TS_IP:$PORT\"
listen-http: \"$TS_IP:$PORT\"
behind-proxy: false
auth-file: \"$CONF/user.db\"
auth-default-access: deny-all
enable-login: false
enable-signup: false
attachment-cache-dir: \"$CONF/attachments\"
cache-file: \"$CONF/cache.db\"
EOF
chmod 0600 $CONF/server.yml && echo '  config written'"

say "4) install unit + start server (first start creates the auth DB)"
"${SCP[@]}" "$REPO_ROOT/infra/systemd/ntfy.service" "$HUB:/etc/systemd/system/ntfy.service"
"${SSH[@]}" "set -e; systemctl daemon-reload
  systemctl enable --now ntfy.service
  for i in 1 2 3 4 5 6 7 8 9 10; do
    [ -f $CONF/user.db ] && break
    sleep 1
  done
  [ -f $CONF/user.db ] && echo '  ntfy active, auth DB ready'"

say "5) provision users + publisher token (idempotent, values never echoed)"
# The admin password arrives on STDIN (the local env does not cross SSH, and
# argv would expose it in the hub's process list). It lands in a 0600 file on
# tmpfs (/run), feeds NTFY_PASSWORD, and is removed immediately.
printf '%s' "${CAMELOT_NTFY_ADMIN_PASSWORD:-}" | "${SSH[@]}" "set -e; cat > /run/camelot-ntfy-pw
  export NTFY_CONFIG_FILE=$CONF/server.yml
  if ! /usr/local/bin/ntfy user list 2>/dev/null | grep -q '^ *admin '; then
    if ! [ -s /run/camelot-ntfy-pw ]; then
      echo '  FATAL: CAMELOT_NTFY_ADMIN_PASSWORD required on first run' >&2
      exit 1
    fi
    chmod 0600 /run/camelot-ntfy-pw
    NTFY_PASSWORD=\"\$(cat /run/camelot-ntfy-pw)\" /usr/local/bin/ntfy user add --role=admin admin >/dev/null
    echo '  admin user created (management plane)'
  else
    echo '  admin user exists - credentials untouched'
  fi
  if ! /usr/local/bin/ntfy user list 2>/dev/null | grep -q '^ *alerts '; then
    NTFY_PASSWORD=\"\$(head -c 24 /dev/urandom | od -An -tx1 | tr -d ' \\n')\" /usr/local/bin/ntfy user add --role=user alerts >/dev/null
    echo '  alerts user created'
  else
    echo '  alerts user exists'
  fi
  /usr/local/bin/ntfy access alerts '$TOPIC' write-only >/dev/null
  echo '  alerts user: write-only on $TOPIC'
  rm -f /run/camelot-ntfy-pw
  # "token add" prints: token tk_... created for user alerts, ...
  # The secret is field 2 - the LAST field is the word "expires" (bug shipped once).
  TOK=\$(/usr/local/bin/ntfy token add --label camelot-alert-unit alerts | awk '{print \$2}')
  case \"\$TOK\" in
    tk_*) echo '  publisher token generated (tk_* shape verified)' ;;
    *) echo '  FATAL: token shape unexpected - refusing to install' >&2; exit 1 ;;
  esac
  mkdir -p /etc/systemd/system/camelot-selfcheck-alert.service.d
  printf '[Service]\nEnvironment=CAMELOT_ALERT_WEBHOOK=http://$TS_IP:$PORT/$TOPIC\nEnvironment=CAMELOT_ALERT_NTFY_MODE=1\nEnvironment=CAMELOT_ALERT_NTFY_TOKEN=%s\n' \"\$TOK\" \
    > /etc/systemd/system/camelot-selfcheck-alert.service.d/ntfy-channel.conf
  chmod 0600 /etc/systemd/system/camelot-selfcheck-alert.service.d/ntfy-channel.conf
  echo '  publisher token written to root-only drop-in (0600), never displayed'"

say "6) verify: anonymous DENIED, token publish OK"
"${SSH[@]}" "set -e; anon=\$(curl -s -o /dev/null -w '%{http_code}' -m 8 --data-binary 'anon-probe' http://$TS_IP:$PORT/$TOPIC)
  tok=\$(curl -s -o /dev/null -w '%{http_code}' -m 8 -H \"Authorization: Bearer \$(grep -oP '(?<=CAMELOT_ALERT_NTFY_TOKEN=).*' /etc/systemd/system/camelot-selfcheck-alert.service.d/ntfy-channel.conf)\" --data-binary 'token-probe' http://$TS_IP:$PORT/$TOPIC)
  echo \"  anonymous publish -> HTTP \$anon (want 403)\"
  echo \"  token publish     -> HTTP \$tok (want 200)\"
  [ \"\$anon\" = '403' ] && [ \"\$tok\" = '200' ]"

say "7) retire the public ntfy.sh channel"
"${SSH[@]}" "sed -i '/Environment=CAMELOT_ALERT_WEBHOOK=https:\/\/ntfy.sh\/camelot_Alert/d' \
    /etc/systemd/system/camelot-selfcheck-alert.service.d/override.conf 2>/dev/null || true
  systemctl daemon-reload
  echo '  public ntfy.sh channel removed from drop-ins'"

say "8) end-to-end: fire the real alert path"
"${SSH[@]}" "rm -f /var/lib/camelot/selfcheck/last-alert.signature
  systemctl start camelot-selfcheck-alert.service
  sleep 5
  journalctl -u camelot-selfcheck-alert.service --since '1 minute ago' --no-pager -o cat | grep -E 'ALERT emitted' | tail -1"

say "done - subscribe from your phone (tailnet required); URL+token are in the drop-in on the hub, topic '$TOPIC'"
