// Code generated by contracts/gen/generate.mjs. DO NOT EDIT.
// Source of truth: integration/contracts/skills.manifest.json
// Regenerate with `make generate`; `make test` fails on drift.

import type { SkillTier } from './types.js';

export const MANIFEST_VERSION = 1;
export const MANIFEST_POLICY_VERSION = "v1";

/** How far a skill's consequences reach outside this process. */
export type SkillEffect = 'read_only' | 'local_effect' | 'remote_effect';

export interface SkillDefinition {
  readonly id: string;
  readonly version: number;
  readonly tier: SkillTier;
  readonly effect: SkillEffect;
  /** tier >= 2: the broker requires an approved lease. */
  readonly effectful: boolean;
  /** effect !== 'read_only': something outside this process changes. */
  readonly durable: boolean;
  readonly confirmationRequired: boolean;
  /** Lower-cased trigger phrases; longest match wins, then priority. */
  readonly phrases: readonly string[];
  readonly priority: number;
  readonly idempotency: 'natural' | 'lease_single_use';
  readonly retry: 'safe' | 'never';
  readonly artifactKind: string;
  readonly auditKind: string;
  readonly redactTranscript: boolean;
}

export const SKILLS: readonly SkillDefinition[] = [
  {
    id: "ops.staging.read",
    version: 1,
    tier: 1,
    effect: "read_only",
    effectful: false,
    durable: false,
    confirmationRequired: false,
    phrases: ["staging status", "staging"],
    priority: 0,
    idempotency: "natural",
    retry: "safe",
    artifactKind: "staging_status",
    auditKind: "tool.executed",
    redactTranscript: false,
  },
  {
    id: "deployment.review.prepare",
    version: 1,
    tier: 2,
    effect: "read_only",
    effectful: true,
    durable: false,
    confirmationRequired: false,
    phrases: ["deployment review", "deploy review"],
    priority: 0,
    idempotency: "natural",
    retry: "safe",
    artifactKind: "deployment_review_draft",
    auditKind: "tool.executed",
    redactTranscript: true,
  },
  {
    id: "change_request.create",
    version: 1,
    tier: 3,
    effect: "read_only",
    effectful: true,
    durable: false,
    confirmationRequired: true,
    phrases: ["change request"],
    priority: 0,
    idempotency: "natural",
    retry: "safe",
    artifactKind: "change_request",
    auditKind: "tool.executed",
    redactTranscript: true,
  },
  {
    id: "notes.local.write",
    version: 1,
    tier: 2,
    effect: "local_effect",
    effectful: true,
    durable: true,
    confirmationRequired: false,
    phrases: ["save a note", "write a note", "note this"],
    priority: 10,
    idempotency: "lease_single_use",
    retry: "never",
    artifactKind: "local_note",
    auditKind: "tool.executed",
    redactTranscript: true,
  },
] as const;

export function skillById(id: string): SkillDefinition | null {
  return SKILLS.find((s) => s.id === id) ?? null;
}
