# SPDX-License-Identifier: MIT
"""
Mission Layout — per-mission artifact isolation under runtime_state
====================================================================

Gives the OMNI_FORGE_SUPER_AGENT factory (and any other mission runner) a
deterministic, hash-pinned workspace that never touches governance docs.

Location contract
-----------------
    03_VAULT/runtime_state/missions/<mission_id>/
      mission.json                intent snapshot (id, objective, steps, status)
      blueprint.json              frozen schemas/types/HLD        (Step_2 artifact)
      task_dag.json               decomposed task DAG             (Step_3 artifact)
      skills_manifest.json        per-mission tool contracts      (Step_4 artifact)
      verification.json           crucible/Rigor Ladder results   (Step_5 artifact)
      receipts/                   hash-pinned step receipts (append-only naming)

Governance guard: `docs/blueprint.md`, `docs/task.md`, `docs/verification.md`,
and any `PROVENANCE_LEDGER.md` are NEVER written by this module. The factory
emits its per-mission artifacts under runtime_state; the governance docs stay
authoritative at the repo level. (AGENTS.md: governance artifacts are not
regenerated by agent flows.)

Hash pinning: every `write_artifact` returns a sha256 receipt. `verify_mission`
re-hashes each artifact and compares against the mission manifest, so any
post-hoc mutation is detectable.

Run as module:
    python -m control_plane.mission_layout --test
"""
from __future__ import annotations

__version__ = "1.0.0"

import argparse
import hashlib
import json
import re
import sys
import time
from pathlib import Path
from typing import Any

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

CAMELOT_HOME = Path(__file__).resolve().parent.parent
RUNTIME_STATE = CAMELOT_HOME / "03_VAULT" / "runtime_state"
MISSIONS_ROOT = RUNTIME_STATE / "missions"

# ---------------------------------------------------------------------------
# Governance guard
# ---------------------------------------------------------------------------

# Basenames that must NEVER be written by mission artifacts, at any depth.
GOVERNANCE_DOC_BASENAMES = frozenset(
    {
        "PROVENANCE_LEDGER.md",
        "HELIO_PATCH.json",
        "config.json",
        "omnivoice-router.js",
    }
)

# Directory names where governance docs live; never written at any depth.
GOVERNANCE_DOC_DIRS = frozenset({"docs"})

# The five canonical step artifacts a mission may own (basename: description).
MISSION_ARTIFACTS: dict[str, str] = {
    "blueprint.json": "Frozen schemas, types, and high-level design (Step_2)",
    "task_dag.json": "Decomposed task DAG for swarm squire execution (Step_3)",
    "skills_manifest.json": "Per-mission tool contracts and runtime boundaries (Step_4)",
    "verification.json": "Crucible / Rigor Ladder results (Step_5)",
    "receipts": "Append-only hash-pinned step receipts",
}

_MISSION_ID_RE = re.compile(r"^[a-z0-9][a-z0-9_-]{2,63}$")


def is_governance_path(path: Path) -> bool:
    """True if `path` must never be written by a mission artifact writer.

    Two rules, cheapest first:
      1. Basename match — governance basenames are protected wherever they
         live, including the root and mirrored ledger copies.
      2. Ancestor match — docs/ is governance territory at any depth, so
         docs/blueprint.md, docs/task.md, docs/verification.md and friends
         are covered without enumerating them.
    """
    if path.name in GOVERNANCE_DOC_BASENAMES:
        return True
    return any(part in GOVERNANCE_DOC_DIRS for part in path.parts)


def _sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as fh:
        for chunk in iter(lambda: fh.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()


# ---------------------------------------------------------------------------
# Mission session
# ---------------------------------------------------------------------------


class MissionLayoutError(ValueError):
    """Raised when a mission operation would violate the layout contract."""


class MissionSession:
    """Scoped writer for one mission's artifact tree.

    Every write is (a) confined to the mission directory, (b) refused for
    governance paths (defense in depth — the path check runs even though the
    root is already runtime_state/missions), and (c) hash-pinned via a
    receipt. Receipts are append-only: `receipts/NN_step.json` never
    overwrites an existing step number.
    """

    def __init__(self, mission_id: str, objective: str = "", root: Path | None = None):
        mid = (mission_id or "").strip()
        if not _MISSION_ID_RE.match(mid):
            raise MissionLayoutError(
                f"invalid mission_id {mission_id!r}: must match {_MISSION_ID_RE.pattern}"
            )
        self.mission_id = mid
        self.objective = objective
        self.root = (root or (MISSIONS_ROOT / mid)).resolve()
        self.manifest_path = self.root / "mission.json"
        self.receipts: list[dict[str, Any]] = []

    # -- path safety ---------------------------------------------------------

    def _safe_child(self, relative: str) -> Path:
        rel = Path(relative)
        if rel.is_absolute() or ".." in rel.parts:
            raise MissionLayoutError(f"artifact path escapes mission root: {relative!r}")
        target = (self.root / rel).resolve()
        if target != self.root and self.root not in target.parents:
            raise MissionLayoutError(f"artifact path escapes mission root: {relative!r}")
        if is_governance_path(target):
            raise MissionLayoutError(f"refusing to write governance path: {target}")
        return target

    # -- lifecycle -----------------------------------------------------------

    def create(self, steps: list[str] | None = None) -> dict[str, Any]:
        """Scaffold the mission directory and manifest. Idempotent."""
        if is_governance_path(self.root):
            raise MissionLayoutError(
                f"refusing to create mission inside governance territory: {self.root}"
            )
        self.root.mkdir(parents=True, exist_ok=True)
        (self.root / "receipts").mkdir(exist_ok=True)
        manifest = {
            "schema": "camelot.mission/1",
            "mission_id": self.mission_id,
            "objective": self.objective,
            "steps": steps
            or [
                "OBSERVE_AND_SCAFFOLD",
                "ARCHITECT_BLUEPRINT",
                "DECOMPOSE_TASK_DAG",
                "EQUIP_KNIGHTS",
                "VALIDATION_SWARM",
            ],
            "status": "OPEN",
            "artifacts": {},
            "created_at": _now(),
        }
        if self.manifest_path.exists():
            existing = json.loads(self.manifest_path.read_text(encoding="utf-8"))
            existing.setdefault("status", "OPEN")
            self.manifest_path.write_text(
                json.dumps(existing, indent=2, ensure_ascii=False), encoding="utf-8"
            )
            return existing
        self.manifest_path.write_text(
            json.dumps(manifest, indent=2, ensure_ascii=False), encoding="utf-8"
        )
        return manifest

    def load_manifest(self) -> dict[str, Any]:
        if not self.manifest_path.exists():
            raise MissionLayoutError(f"mission not initialized: {self.mission_id}")
        return json.loads(self.manifest_path.read_text(encoding="utf-8"))

    # -- artifact writes -----------------------------------------------------

    def write_artifact(self, name: str, payload: Any) -> dict[str, Any]:
        """Write a mission artifact + append-only receipt. Returns the receipt.

        `name` must be one of the canonical MISSION_ARTIFACTS basenames
        (or `receipts/…`), keeping the layout deterministic for the crucible.
        """
        if name not in MISSION_ARTIFACTS:
            raise MissionLayoutError(
                f"unknown artifact {name!r}; canonical set: {sorted(MISSION_ARTIFACTS)}"
            )
        target = self._safe_child(name)
        target.write_text(json.dumps(payload, indent=2, ensure_ascii=False), encoding="utf-8")
        try:
            rel_path = str(target.relative_to(CAMELOT_HOME))
        except ValueError:  # external root (e.g. test tempdir) — keep absolute
            rel_path = str(target)
        receipt = {
            "artifact": name,
            "path": rel_path,
            "sha256": _sha256_file(target),
            "bytes": target.stat().st_size,
            "written_at": _now(),
        }
        self._append_receipt(receipt)

        manifest = self.load_manifest()
        manifest.setdefault("artifacts", {})[name] = receipt["sha256"]
        self.manifest_path.write_text(
            json.dumps(manifest, indent=2, ensure_ascii=False), encoding="utf-8"
        )
        return receipt

    def _append_receipt(self, receipt: dict[str, Any]) -> None:
        receipts_dir = self.root / "receipts"
        n = 1
        while (receipts_dir / f"{n:03d}_step.json").exists():
            n += 1
        entry = dict(receipt)
        entry["receipt_no"] = n
        (receipts_dir / f"{n:03d}_step.json").write_text(
            json.dumps(entry, indent=2, ensure_ascii=False), encoding="utf-8"
        )
        self.receipts.append(entry)

    # -- status / verification ------------------------------------------------

    def set_status(self, status: str) -> dict[str, Any]:
        manifest = self.load_manifest()
        manifest["status"] = status
        manifest["updated_at"] = _now()
        self.manifest_path.write_text(
            json.dumps(manifest, indent=2, ensure_ascii=False), encoding="utf-8"
        )
        return manifest

    def verify_mission(self) -> dict[str, Any]:
        """Re-hash every registered artifact against the mission manifest."""
        manifest = self.load_manifest()
        results: list[dict[str, Any]] = []
        ok = True
        for name, expected_hash in sorted(manifest.get("artifacts", {}).items()):
            path = self.root / name
            if not path.exists():
                results.append({"artifact": name, "status": "MISSING"})
                ok = False
                continue
            actual = _sha256_file(path)
            status = "PINNED" if actual == expected_hash else "MUTATED"
            if status != "PINNED":
                ok = False
            results.append(
                {"artifact": name, "status": status, "sha256": actual}
            )
        return {"mission_id": self.mission_id, "ok": ok, "artifacts": results}


def _now() -> str:
    return time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def _self_test() -> int:
    import tempfile

    failures: list[str] = []

    def check(label: str, cond: bool) -> None:
        print(f"  {'PASS' if cond else 'FAIL'}  {label}")
        if not cond:
            failures.append(label)

    print(f"[mission_layout v{__version__}] self-test")
    with tempfile.TemporaryDirectory() as td:
        tmp_root = Path(td)

        # 1. governance guard
        check(
            "governance: docs/blueprint.md protected",
            is_governance_path(tmp_root / "docs" / "blueprint.md"),
        )
        check(
            "governance: nested docs/task.md protected",
            is_governance_path(tmp_root / "a" / "docs" / "task.md"),
        )
        check(
            "governance: ledger basename protected anywhere",
            is_governance_path(tmp_root / "x" / "PROVENANCE_LEDGER.md"),
        )
        check(
            "governance: mission blueprint.json NOT protected",
            not is_governance_path(tmp_root / "missions" / "m1" / "blueprint.json"),
        )

        session = MissionSession("self_test_mission", objective="layout self-test", root=tmp_root / "missions" / "self_test_mission")
        session.create()
        check("create: manifest exists", session.manifest_path.exists())
        receipt = session.write_artifact("blueprint.json", {"frozen": True})
        check("write: receipt has sha256", bool(receipt.get("sha256")))

        manifest = session.load_manifest()
        check("manifest pins artifact", manifest["artifacts"].get("blueprint.json") == receipt["sha256"])

        verdict = session.verify_mission()
        check("verify: PINNED ok", verdict["ok"] and verdict["artifacts"][0]["status"] == "PINNED")

        # mutation detection
        bp = session.root / "blueprint.json"
        bp.write_text('{"frozen": false}', encoding="utf-8")
        verdict2 = session.verify_mission()
        check(
            "verify: MUTATION detected",
            (not verdict2["ok"]) and verdict2["artifacts"][0]["status"] == "MUTATED",
        )

        # guards (rewrite of a canonical artifact is allowed; escape is not)
        try:
            session._safe_child("../../docs/blueprint.md")
            escape_blocked = False
        except MissionLayoutError:
            escape_blocked = True
        check("guard: path escape blocked", escape_blocked)
        try:
            session.write_artifact("task.md", {"x": 1})
            unknown_blocked = False
        except MissionLayoutError:
            unknown_blocked = True
        check("guard: unknown artifact refused", unknown_blocked)

    if failures:
        print(f"[mission_layout] {len(failures)} FAILURE(S)")
        return 1
    print("[mission_layout] ALL PASS")
    return 0


def _run_demo(mission_id: str | None = None) -> int:
    """Run one OMNI_FORGE factory mission end-to-end through the 5 DAG steps.

    Writes only canonical artifacts under runtime_state/missions/<id>/ —
    governance docs stay untouched by construction.
    """
    mid = (mission_id or f"omni-forge-demo-{time.strftime('%Y%m%d')}").strip()
    session = MissionSession(mid, objective="OMNI_FORGE 5-step factory DAG loop (demo)")
    print(f"[demo] mission_id={mid}")
    print(f"[demo] root={session.root}")

    # Step 1 — OBSERVE_AND_SCAFFOLD: intent snapshot + folder architecture
    manifest = session.create()
    print(f"  [1/5] OBSERVE_AND_SCAFFOLD  -> mission.json ({len(manifest['steps'])} steps)")

    # Step 2 — ARCHITECT_BLUEPRINT: freeze schemas/types/HLD
    blueprint = {
        "step": "ARCHITECT_BLUEPRINT",
        "frozen": {
            "schemas": {"Mission": "camelot.mission/1", "Receipt": "append-only sha256"},
            "types": ["mission_id: slug", "artifact: canonical-set", "sha256: hex64"],
            "hld": "Per-mission runtime_state isolation; governance docs immutable",
        },
        "governance_writes": "forbidden",
    }
    r2 = session.write_artifact("blueprint.json", blueprint)
    print(f"  [2/5] ARCHITECT_BLUEPRINT   -> blueprint.json {r2['sha256'][:12]}...")

    # Step 3 — DECOMPOSE_TASK_DAG: parallel squire execution sequences
    task_dag = {
        "step": "DECOMPOSE_TASK_DAG",
        "nodes": [
            {"id": "n1", "task": "parse intent", "assignee": "squire_scan"},
            {"id": "n2", "task": "extract symbols", "assignee": "squire_index", "after": ["n1"]},
            {"id": "n3", "task": "emit artifacts", "assignee": "squire_mason", "after": ["n2"]},
        ],
        "parallel_sequences": [["n1"], ["n2"], ["n3"]],
    }
    r3 = session.write_artifact("task_dag.json", task_dag)
    print(f"  [3/5] DECOMPOSE_TASK_DAG    -> task_dag.json {r3['sha256'][:12]}...")

    # Step 4 — EQUIP_KNIGHTS: per-mission tool contracts (referenced, not injected)
    skills = {
        "step": "EQUIP_KNIGHTS",
        "contracts": [
            {"knight": "sir_forge", "tools": ["write_artifact", "verify_mission"], "boundary": "missions/<id>/ only"},
            {"knight": "merlin_omega", "tools": ["run_crucible"], "boundary": "verification.json write-only"},
            {"knight": "anya_gate", "tools": ["is_governance_path"], "boundary": "gatekeeper, read-only"},
        ],
        "note": "Global skills surface stays immutable; squires reference this manifest.",
    }
    r4 = session.write_artifact("skills_manifest.json", skills)
    print(f"  [4/5] EQUIP_KNIGHTS         -> skills_manifest.json {r4['sha256'][:12]}...")

    # Step 5 — VALIDATION_SWARM: rigor ladder results + hash-pin verification
    verification = {
        "step": "VALIDATION_SWARM",
        "rigor_ladder": {"L4": "cross-verified proof", "L3": "property battery", "L2": "SMT bound", "L1": "self-test"},
        "results": {
            "mission_layout_self_test": "11/11 PASS",
            "governance_guard": "docs/ and ledger basenames blocked at any depth",
        },
    }
    r5 = session.write_artifact("verification.json", verification)
    print(f"  [5/5] VALIDATION_SWARM      -> verification.json {r5['sha256'][:12]}...")

    verdict = session.verify_mission()
    final_status = "SEALED" if verdict["ok"] else "DRIFT"
    session.set_status(final_status)
    print(f"[demo] verify_mission ok={verdict['ok']} pinned_artifacts={len(verdict['artifacts'])}")
    print(f"[demo] status={final_status} receipts={len(session.receipts)} (append-only)")
    return 0 if verdict["ok"] else 1


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(prog="mission_layout")
    ap.add_argument("--test", action="store_true", help="run self-test")
    ap.add_argument("--demo", action="store_true", help="run one demo factory mission into runtime_state")
    ap.add_argument("--mission-id", help="mission id for --demo (default: omni-forge-demo-<date>)")
    args = ap.parse_args(argv)
    if args.test:
        return _self_test()
    if args.demo:
        return _run_demo(args.mission_id)
    ap.print_help()
    return 0


if __name__ == "__main__":
    sys.exit(main())
