import type { CartridgeManifest } from "./types";

export const cartridgeManifests: CartridgeManifest[] = [
  {
    id: "command",
    label: "Sovereign Command",
    shortLabel: "Command",
    description: "Operator intent, runtime truth, and governed execution.",
    lead: "Anya + Sir Alex",
    phaseGlyph: "[EXECUTE]",
    accent: "teal",
    capabilities: ["runtime.read", "intent.route", "approval.request"],
  },
  {
    id: "factory",
    label: "Creation Factory",
    shortLabel: "Factory",
    description: "Blueprint OS production flow and Bio-Kinetic delivery lanes.",
    lead: "Sir Forge + Sir Codex",
    phaseGlyph: "[COLONY]",
    accent: "amber",
    capabilities: ["blueprint.read", "swarm.observe", "build.verify"],
  },
  {
    id: "forge-law",
    label: "Forge Queue",
    shortLabel: "Forge",
    description: "Verified upgrades, immutable execution DAGs, and rollback evidence.",
    lead: "LUKAS + Sir Sentinel",
    phaseGlyph: "[EXECUTE]",
    accent: "coral",
    capabilities: ["cartridge.crystallize", "dag.inspect", "approval.request", "rollback.observe"],
  },
  {
    id: "intelligence",
    label: "Cloud Intelligence",
    shortLabel: "Intel",
    description: "NotebookLM guidance, memory health, and briefing provenance.",
    lead: "Lady Mnemosyne",
    phaseGlyph: "[PLAN]",
    accent: "blue",
    capabilities: ["notebook.read", "memory.inspect", "briefing.render"],
  },
  {
    id: "interphase",
    label: "Live Interphase",
    shortLabel: "Live",
    description: "Local voice, visual context, interruption, and session resilience.",
    lead: "Anya + Sir Helio",
    phaseGlyph: "[LIVE]",
    accent: "teal",
    capabilities: ["voice.interrupt", "vision.capture-local", "session.reset", "transport.observe"],
  },
  {
    id: "device-hall",
    label: "Device Hall",
    shortLabel: "Devices",
    description: "Signed companion enrollment, capability grants, and hardware receipts.",
    lead: "Sir Sentinel + Sir Link",
    phaseGlyph: "[VALIDATE]",
    accent: "amber",
    capabilities: ["device.enroll", "capability.grant", "action.approve", "device.revoke"],
  },
  {
    id: "mesh",
    label: "Cartridge Mesh",
    shortLabel: "Mesh",
    description: "Trusted micro-frontend catalog, bridge topology, and service health.",
    lead: "Sir Link + Sentinel",
    phaseGlyph: "[VALIDATE]",
    accent: "coral",
    capabilities: ["cartridge.mount", "topology.read", "policy.inspect"],
  },
];
