-- Migration: Phase 10 Agency Factory
-- Generated by Merlin_Omega

CREATE TABLE IF NOT EXISTS `users` (
    `id` text PRIMARY KEY NOT NULL,
    `email` text NOT NULL UNIQUE,
    `role` text DEFAULT 'CLIENT',
    `created_at` integer
);

CREATE TABLE IF NOT EXISTS `agency_deliverables` (
    `id` text PRIMARY KEY NOT NULL,
    `user_id` text REFERENCES `users`(`id`),
    `type` text NOT NULL,
    `status` text DEFAULT 'PENDING',
    `path` text,
    `created_at` integer
);

-- Index for faster lookups by user
CREATE INDEX IF NOT EXISTS `idx_deliverables_user_id` ON `agency_deliverables` (`user_id`);
