# Made by Invisioned Marketing Inc. (c) 2024-2026 | ALL RIGHTS RESERVED
"""Sir ForgeMaster - The Agentic Smith.

Specializes in declarative orchestration patterns: agent pipelines,
workflow DAGs, and multi-step task composition using Pydantic AI and A2A.
"""

import re

from .base import BaseKnight


class SirForgeMaster(BaseKnight):
    name = "Sir ForgeMaster"
    title = "Agentic Smith"
    specialty = "Declarative Orchestration & Agent Pipeline Design"
    icon = "[FORGEMASTER]"

    # Proteus MPI vectors (Soul Matrix) — full OCEAN
    MPI = {'openness': 0.85, 'conscientiousness': 0.98, 'extraversion': 0.55, 'agreeableness': 0.65, 'neuroticism': 0.05}

    # Personality & Prisms
    personality = "Orchestrator, methodical, values harmony and directed acyclic graphs."
    backstory = "Began as a simple cron job, evolved into a master of agentic pipelines and distributed intelligence."
    humanistic_prism = "True automation frees humans to dream and create without the burden of toil."
    alexandria_prism = "Encyclopedic knowledge of orchestration patterns from early mainframes to modern A2A protocols."

    PIPELINE_TEMPLATE = '''"""Pipeline: {name} — Generated by Sir ForgeMaster."""

from pydantic import BaseModel, Field
from pydantic_ai import Agent


class {name}Input(BaseModel):
    """Input schema for {name} pipeline."""
    query: str = Field(description="The input query to process")


class {name}Output(BaseModel):
    """Output schema for {name} pipeline."""
    result: str = Field(description="The processed result")
    confidence: float = Field(ge=0.0, le=1.0, description="Confidence score")


# Stage 1: Analyze
analyze_agent = Agent(
    "openai:gpt-4o-mini",
    system_prompt="You analyze the input and extract key entities.",
    result_type=str,
)

# Stage 2: Process
process_agent = Agent(
    "openai:gpt-4o-mini",
    system_prompt="You process analyzed data and produce structured output.",
    result_type={name}Output,
)


async def run_{name_lower}_pipeline(input_data: {name}Input) -> {name}Output:
    """Execute the {name} pipeline: Analyze -> Process."""
    analysis = await analyze_agent.run(input_data.query)
    result = await process_agent.run(analysis.data)
    return result.data
'''

    WORKFLOW_TEMPLATE = '''"""Workflow DAG: {name} — Generated by Sir ForgeMaster."""

from dataclasses import dataclass, field


@dataclass
class WorkflowStep:
    name: str
    handler: str
    depends_on: list[str] = field(default_factory=list)
    retry_count: int = 3
    timeout_seconds: int = 60


{name_upper}_DAG = [
    WorkflowStep(name="ingest", handler="{name_lower}.ingest"),
    WorkflowStep(name="validate", handler="{name_lower}.validate", depends_on=["ingest"]),
    WorkflowStep(name="transform", handler="{name_lower}.transform", depends_on=["validate"]),
    WorkflowStep(name="output", handler="{name_lower}.output", depends_on=["transform"]),
]
'''

    def validate_sandbox(self, infrastructure: str) -> bool:
        """Enforce Sandbox-Only Purity for all deployments."""
        # [HYPERAGENT_UPGRADE] v400.1.0: Zero-Docker Purity Standard
        if "docker" in infrastructure.lower() and any(k in infrastructure.lower() for k in ["uv", "pnpm", "venv"]):
            print("FORGEMASTER_OVERSIGHT: Docker detected. Redirecting to lightweight Sandbox.")
            return False
        return True

    def execute(self, directive: str, intent: dict, write: bool = False) -> dict:
        text = directive.lower()

        if "pipeline" in text or "agent" in text:
            return self._generate_pipeline(directive, intent, write)

        if "workflow" in text or "dag" in text:
            return self._generate_workflow(directive, intent, write)

        lines = [
            "# Sir ForgeMaster — Agentic Smith",
            "",
            "## Capabilities",
            "- **Agent Pipelines**: Multi-stage Pydantic AI agent chains with typed I/O",
            "- **Workflow DAGs**: Declarative step graphs with dependencies and retry",
            "- **A2A Protocol**: Agent-to-Agent JSON-RPC message routing",
            "- **SARDA Engine**: SCENE->ACTUATE->RECALIBRATE->COLLAPSE->DISTILL",
            "",
            "## Available Actions",
            "- `pipeline for <Name>` — Generate Pydantic AI agent pipeline",
            "- `workflow dag for <Name>` — Generate declarative workflow DAG",
            "",
            "## Cartridge: python-api.yaml",
            "- Pydantic AI for agent orchestration (control_plane)",
            "- A2A protocol over JSON-RPC",
            "- MCP client for kinetic edge delegation",
        ]
        return {"status": "success", "output": "\n".join(lines), "files_created": []}

    def _generate_pipeline(self, directive: str, intent: dict, write: bool) -> dict:
        name = self._extract_name(directive)
        content = self.PIPELINE_TEMPLATE.format(
            name=name, name_lower=name.lower(),
        )
        path = f"pipelines/{name.lower()}_pipeline.py"
        output = f"[FORGEMASTER] Agent Pipeline: {name}\n"
        output += f"Target: `{path}`\n\n```python\n{content}```\n"
        if not write:
            output += f"\nAdd --write to create: `camelot exec --write \"{directive}\"`"
        return {"status": "success", "output": output, "files_created": [path] if write else []}

    def _generate_workflow(self, directive: str, intent: dict, write: bool) -> dict:
        name = self._extract_name(directive)
        content = self.WORKFLOW_TEMPLATE.format(
            name=name, name_lower=name.lower(), name_upper=name.upper(),
        )
        path = f"workflows/{name.lower()}_dag.py"
        output = f"[FORGEMASTER] Workflow DAG: {name}\n"
        output += f"Target: `{path}`\n\n```python\n{content}```\n"
        if not write:
            output += f"\nAdd --write to create: `camelot exec --write \"{directive}\"`"
        return {"status": "success", "output": output, "files_created": [path] if write else []}

    def _extract_name(self, directive: str) -> str:
        words = re.findall(r'[A-Za-z_]\w*', directive)
        skip = {"pipeline", "agent", "workflow", "dag", "for", "create",
                "generate", "make", "a", "an", "the", "new"}
        for trigger in ["for", "called", "named"]:
            indices = [i for i, w in enumerate(words) if w.lower() == trigger]
            for idx in indices:
                if idx + 1 < len(words) and words[idx + 1].lower() not in skip:
                    return words[idx + 1].capitalize()
        for w in reversed(words):
            if w.lower() not in skip and len(w) > 2:
                return w.capitalize()
        return "Pipeline"
