# Made by Invisioned Marketing Inc. (c) 2024-2026 | ALL RIGHTS RESERVED
"""Sir Lancelot - The Master Builder.

Specializes in system design, architectural integrity, and module boundary
enforcement. Generates system diagrams, dependency maps, and module contracts.
"""

import ast
import re
from pathlib import Path

from .base import BaseKnight


class SirLancelot(BaseKnight):
    name = "Sir Lancelot"
    title = "Master Builder"
    specialty = "System Design & Architectural Integrity"
    icon = "[LANCELOT]"

    MODULE_CONTRACT_TEMPLATE = '''"""{name} Module Contract — Generated by Sir Lancelot.

Public Interface:
{exports}

Dependencies:
{dependencies}

Invariants:
{invariants}
"""
'''

    def execute(self, directive: str, intent: dict, write: bool = False) -> dict:
        text = directive.lower()
        params = intent.get("parameters", {})
        target_path = params.get("path", "")

        # Dependency map
        if "dependency" in text or "dep map" in text or "imports" in text:
            if target_path:
                return self._dependency_map(target_path)
            return self._dependency_map_guide()

        # Module contract
        if "contract" in text or "interface" in text or "boundary" in text:
            return self._module_contract(directive, intent, write)

        # System diagram (Mermaid)
        if "diagram" in text or "architecture" in text or "mermaid" in text:
            return self._system_diagram(directive, intent)

        # Integrity audit
        if "audit" in text or "integrity" in text or "drift" in text:
            return self._integrity_audit()

        lines = [
            "# Sir Lancelot — Master Builder",
            "",
            "## Domains",
            "- **Dependency Mapping**: Import graph analysis for Python modules",
            "- **Module Contracts**: Formal interface definitions with invariants",
            "- **System Diagrams**: Mermaid architecture visualizations",
            "- **Integrity Audit**: Architectural drift detection",
            "",
            "## Available Actions",
            "- `dependency map <path>` — Analyze import graph for a Python file",
            "- `contract for <module>` — Generate module contract template",
            "- `diagram for <system>` — Generate Mermaid architecture diagram",
            "- `integrity audit` — Check for architectural drift",
        ]
        return {"status": "success", "output": "\n".join(lines), "files_created": []}

    def _dependency_map(self, target_path: str) -> dict:
        lines = [f"[LANCELOT] Dependency Map: `{target_path}`", ""]

        try:
            abs_path = Path(target_path).expanduser().resolve()
            if abs_path.exists() and abs_path.suffix == ".py":
                source = abs_path.read_text(encoding="utf-8", errors="replace")
                tree = ast.parse(source)

                imports = []
                for node in ast.walk(tree):
                    if isinstance(node, ast.Import):
                        for alias in node.names:
                            imports.append(("import", alias.name, alias.asname))
                    elif isinstance(node, ast.ImportFrom):
                        module = node.module or ""
                        for alias in node.names:
                            imports.append(("from", f"{module}.{alias.name}", alias.asname))

                stdlib = []
                local = []
                third_party = []

                for kind, name, alias in imports:
                    top = name.split(".")[0]
                    if top.startswith(".") or top in ("knights", "control_plane", "squires", "ouroboros"):
                        local.append((kind, name, alias))
                    else:
                        # Simple heuristic: common stdlib modules
                        _STDLIB = {"os", "sys", "re", "ast", "json", "time", "pathlib",
                                   "typing", "abc", "subprocess", "shutil", "hashlib",
                                   "collections", "functools", "itertools", "dataclasses",
                                   "logging", "datetime", "math", "io", "contextlib"}
                        if top in _STDLIB:
                            stdlib.append((kind, name, alias))
                        else:
                            third_party.append((kind, name, alias))

                def _fmt(entries):
                    out = []
                    for kind, name, alias in entries:
                        s = f"  {kind} {name}"
                        if alias:
                            s += f" as {alias}"
                        out.append(s)
                    return "\n".join(out) if out else "  (none)"

                lines.append("### Standard Library")
                lines.append(_fmt(stdlib))
                lines.append("")
                lines.append("### Third-Party")
                lines.append(_fmt(third_party))
                lines.append("")
                lines.append("### Internal (Camelot)")
                lines.append(_fmt(local))
                lines.append("")
                lines.append(f"**Total imports: {len(imports)}** "
                           f"(stdlib: {len(stdlib)}, 3rd-party: {len(third_party)}, internal: {len(local)})")
            else:
                lines.append(f"File not found or not Python: `{target_path}`")
        except Exception as e:
            lines.append(f"[ERROR] {e}")

        return {"status": "success", "output": "\n".join(lines), "files_created": []}

    def _dependency_map_guide(self) -> dict:
        lines = [
            "[LANCELOT] Dependency Mapping Guide",
            "",
            "Provide a file path to analyze:",
            "  `camelot exec dependency map <path>`",
            "",
            "### What Gets Mapped",
            "- Standard library imports",
            "- Third-party package imports",
            "- Internal Camelot module imports",
            "- Import aliases and re-exports",
        ]
        return {"status": "success", "output": "\n".join(lines), "files_created": []}

    def _module_contract(self, directive: str, intent: dict, write: bool) -> dict:
        name = self._extract_name(directive)

        content = self.MODULE_CONTRACT_TEMPLATE.format(
            name=name,
            exports="  - TODO: List public functions/classes",
            dependencies="  - TODO: List required imports",
            invariants="  - TODO: List conditions that must always hold",
        )

        output = f"[LANCELOT] Module Contract: {name}\n\n```python\n{content}```\n"
        output += "### Contract Rules\n"
        output += "- Public interface = only what's in `__all__` or documented exports\n"
        output += "- Dependencies must be explicit (no dynamic imports in public API)\n"
        output += "- Invariants are tested in module-level assertions or unit tests\n"
        output += "- Breaking changes require ADR (route to Sir Synthesis)\n"

        return {"status": "success", "output": output, "files_created": []}

    def _system_diagram(self, directive: str, intent: dict) -> dict:
        topic = re.sub(r"(diagram|architecture|mermaid|for|generate|create)\s*", "",
                       directive, flags=re.I).strip() or "Camelot OS"

        mermaid = f"""```mermaid
graph TB
    subgraph "{topic}"
        A[Client / CLI] --> B[Control Plane<br/>Pydantic AI]
        B --> C[Knight Dispatch]
        C --> D[Sir Boris<br/>Orchestrator]
        C --> E[Sir Forge<br/>Code Gen]
        C --> F[Sir Sentinel<br/>Security]
        C --> G[Sir Debug<br/>Diagnostics]
        B --> H[Kinetic Edge<br/>Rust/Axum MCP]
        H --> I[Saltare<br/>Gateway]
        H --> J[Cribo<br/>Bundler]
        H --> K[Rotel<br/>Telemetry]
        D --> L[Squire Colony<br/>8 Nano-Knights]
        B --> M[(Ouroboros DB<br/>SQLite WAL)]
        B --> N[CLIProxyAPI<br/>29 Models]
    end
```"""

        output = f"[LANCELOT] System Diagram: {topic}\n\n{mermaid}\n"
        output += "\nPaste into any Mermaid renderer (GitHub, Notion, mermaid.live)."

        return {"status": "success", "output": output, "files_created": []}

    def _integrity_audit(self) -> dict:
        lines = [
            "[LANCELOT] Architectural Integrity Audit",
            "",
            "### Layer Violations",
            "- [ ] L2 (Kinetic) does not import from L5 (Agentic)",
            "- [ ] L4 (Cloud) does not directly call L2 (Local) without bridge",
            "- [ ] L6 (Governance) is read-only from lower layers",
            "",
            "### Boundary Enforcement",
            "- [ ] Knights only access other knights via control_plane dispatch",
            "- [ ] Squires only communicate through Colony CLI pipeline",
            "- [ ] External services accessed through CLIProxyAPI, not direct HTTP",
            "",
            "### Dependency Direction",
            "- [ ] All imports flow downward (higher layers import lower)",
            "- [ ] No circular imports between knight modules",
            "- [ ] BaseKnight contract respected (execute returns dict)",
            "",
            "### Drift Detection",
            "- [ ] roster.yaml matches actual knight classes in knights/",
            "- [ ] Control plane KNIGHT_ROUTES covers all active knights",
            "- [ ] Cartridges reference existing patterns (no phantom APIs)",
        ]
        return {"status": "success", "output": "\n".join(lines), "files_created": []}

    def _extract_name(self, directive: str) -> str:
        words = re.findall(r'[A-Za-z_]\w*', directive)
        skip = {"contract", "interface", "boundary", "module", "for", "create",
                "generate", "make", "a", "an", "the", "new"}
        for trigger in ["for", "called", "named"]:
            indices = [i for i, w in enumerate(words) if w.lower() == trigger]
            for idx in indices:
                if idx + 1 < len(words) and words[idx + 1].lower() not in skip:
                    return words[idx + 1].capitalize()
        for w in reversed(words):
            if w.lower() not in skip and len(w) > 2:
                return w.capitalize()
        return "Module"
