// Code generated by contracts/gen/generate.mjs. DO NOT EDIT.
// Source of truth: integration/contracts/skills.manifest.json
// Regenerate with `make generate`; `make test` fails on drift.

package main

// manifestVersion / manifestPolicyVersion pin the catalog the binary was
// built against, so an audit record can be traced to a definition.
const (
	manifestVersion       = 1
	manifestPolicyVersion = "v1"
)

// Skill is one governed capability, as declared in the manifest.
//
//	Effectful — tier >= 2: requires an approved lease before the broker runs it.
//	Durable   — effect != read_only: produces a side effect outside this process.
//
// Effectful and Durable are independent: a tier-2 draft is Effectful (policy
// gates it) but not Durable (nothing outside memory changes).
type Skill struct {
	ID                   string
	Version              int
	Tier                 int
	Effect               string
	Effectful            bool
	Durable              bool
	ConfirmationRequired bool
	Phrases              []string
	Priority             int
	Idempotency          string
	Retry                string
	ArtifactKind         string
	AuditKind            string
	RedactTranscript     bool
}

var skillRegistry = []Skill{
	{
		ID:                   "ops.staging.read",
		Version:              1,
		Tier:                 1,
		Effect:               "read_only",
		Effectful:            false,
		Durable:              false,
		ConfirmationRequired: false,
		Phrases:              []string{"staging status", "staging"},
		Priority:             0,
		Idempotency:          "natural",
		Retry:                "safe",
		ArtifactKind:         "staging_status",
		AuditKind:            "tool.executed",
		RedactTranscript:     false,
	},
	{
		ID:                   "deployment.review.prepare",
		Version:              1,
		Tier:                 2,
		Effect:               "read_only",
		Effectful:            true,
		Durable:              false,
		ConfirmationRequired: false,
		Phrases:              []string{"deployment review", "deploy review"},
		Priority:             0,
		Idempotency:          "natural",
		Retry:                "safe",
		ArtifactKind:         "deployment_review_draft",
		AuditKind:            "tool.executed",
		RedactTranscript:     true,
	},
	{
		ID:                   "change_request.create",
		Version:              1,
		Tier:                 3,
		Effect:               "read_only",
		Effectful:            true,
		Durable:              false,
		ConfirmationRequired: true,
		Phrases:              []string{"change request"},
		Priority:             0,
		Idempotency:          "natural",
		Retry:                "safe",
		ArtifactKind:         "change_request",
		AuditKind:            "tool.executed",
		RedactTranscript:     true,
	},
	{
		ID:                   "notes.local.write",
		Version:              1,
		Tier:                 2,
		Effect:               "local_effect",
		Effectful:            true,
		Durable:              true,
		ConfirmationRequired: false,
		Phrases:              []string{"save a note", "write a note", "note this"},
		Priority:             10,
		Idempotency:          "lease_single_use",
		Retry:                "never",
		ArtifactKind:         "local_note",
		AuditKind:            "tool.executed",
		RedactTranscript:     true,
	},
}
