import { Brain, Code2, Search, Palette, TrendingUp, Scale, Lightbulb, Target } from 'lucide-react';
import type { CartridgeMeta, CartridgeId } from '@/types/camelot';

export const CARTRIDGES: CartridgeMeta[] = [
  {
    id: 'COGNITIVE',
    slug: 'cognitive',
    label: 'Cognitive',
    knight: 'SIR_ALEX',
    color: 'indigo',
    accentHex: '#818cf8',
    borderClass: 'border-indigo-500/40',
    bgClass: 'bg-indigo-950/30',
    textClass: 'text-indigo-300',
    icon: Brain,
    description: 'Reasoning chains, GoT/DoT/ToT orchestration, critical decisions.',
  },
  {
    id: 'ENGINEER',
    slug: 'engineer',
    label: 'Engineer',
    knight: 'SIR_FORGE',
    color: 'emerald',
    accentHex: '#34d399',
    borderClass: 'border-emerald-500/40',
    bgClass: 'bg-emerald-950/30',
    textClass: 'text-emerald-300',
    icon: Code2,
    description: 'Code generation, Rust/Go/Python/TS, debug, refactor, review.',
  },
  {
    id: 'RESEARCH',
    slug: 'research',
    label: 'Research',
    knight: 'LADY_APIS',
    color: 'blue',
    accentHex: '#60a5fa',
    borderClass: 'border-blue-500/40',
    bgClass: 'bg-blue-950/30',
    textClass: 'text-blue-300',
    icon: Search,
    description: 'CHIMERA pipeline, browser scouts, NotebookLM ancestor synthesis.',
  },
  {
    id: 'CREATIVE',
    slug: 'creative',
    label: 'Creative',
    knight: 'SIR_SONUS',
    color: 'pink',
    accentHex: '#f472b6',
    borderClass: 'border-pink-500/40',
    bgClass: 'bg-pink-950/30',
    textClass: 'text-pink-300',
    icon: Palette,
    description: 'Voice synthesis, media production, design, narrative generation.',
  },
  {
    id: 'MARKETING',
    slug: 'marketing',
    label: 'Marketing',
    knight: 'SIR_VALERIAN',
    color: 'orange',
    accentHex: '#fb923c',
    borderClass: 'border-orange-500/40',
    bgClass: 'bg-orange-950/30',
    textClass: 'text-orange-300',
    icon: TrendingUp,
    description: 'Growth strategy, content, SEO, campaigns, ROI analysis.',
  },
  {
    id: 'LEGAL',
    slug: 'legal',
    label: 'Legal',
    knight: 'SIR_SENTINEL',
    color: 'purple',
    accentHex: '#a78bfa',
    borderClass: 'border-purple-500/40',
    bgClass: 'bg-purple-950/30',
    textClass: 'text-purple-300',
    icon: Scale,
    description: 'Contract review, compliance, risk assessment, IP protection.',
  },
  {
    id: 'BRAINSTORM',
    slug: 'brainstorm',
    label: 'Brainstorm',
    knight: 'MERLIN_OMEGA',
    color: 'amber',
    accentHex: '#fbbf24',
    borderClass: 'border-amber-500/40',
    bgClass: 'bg-amber-950/30',
    textClass: 'text-amber-300',
    icon: Lightbulb,
    description: 'Divergent ideation, SCAMPER, TRIZ, cross-domain synthesis.',
  },
  {
    id: 'CRITICAL_THINKING',
    slug: 'critical',
    label: 'Critical',
    knight: 'SIR_ALEX',
    color: 'red',
    accentHex: '#f87171',
    borderClass: 'border-red-500/40',
    bgClass: 'bg-red-950/30',
    textClass: 'text-red-300',
    icon: Target,
    description: "Socratic analysis, Devil's Advocate, bias surfacing, NPE/TCoT.",
  },
];

export const CARTRIDGE_MAP = Object.fromEntries(CARTRIDGES.map((c) => [c.id, c])) as Record<
  CartridgeId,
  CartridgeMeta
>;

export const CARTRIDGE_BY_SLUG = Object.fromEntries(CARTRIDGES.map((c) => [c.slug, c]));
