#!/usr/bin/env python3
# SPDX-License-Identifier: MIT

"""CI / pre-commit gate: the committed OmniVoice Router build artifact must not
drift from its TypeScript source.

`02_FORGE/KINETIC_ARMORY/omnivoice-router/omnivoice-router.js` is a COMMITTED
build artifact (it is the package `main`, and `npm run run-built` executes it).
It is generated by `tsc` via the package's `npm run build`. Nothing regenerates
it automatically, so a contributor who edits `omnivoice-router.ts` and forgets
to rebuild ships a stale router.

That is not hypothetical. As of 2026-09-14 the committed artifact was seven
weeks stale: it predated the entire `/ingest_pcm` HTTP ingest stack and
contained NONE of the binary-frame validation, loopback enforcement, sequence
replay guard, or session-capacity bound. Nothing noticed, because nothing
checked. The VFC crucible had to run the `.ts` through ts-node precisely because
the built artifact could not be trusted.

Why this compares structure rather than bytes:
    A byte-identical comparison would need `tsc` and the package's
    node_modules present, which CI does not install for this package. It would
    also fail on cosmetic churn (whitespace, quoting). Instead this checks the
    three categories where TypeScript's emit is 1:1 and semantically load-bearing:

      * `const UPPER_SNAKE = <numeric | string literal>` — tunables such as
        PCM_FRAME_BYTES and MAX_HTTP_SESSIONS.
      * `error: "<id>"` response identifiers — the wire contract clients match on.
      * `req.url === "<path>"` route paths — the actual surface of the router.

    A missing route or error id, or a changed constant value, in the artifact is
    drift. The authoritative fix is always:

        cd 02_FORGE/KINETIC_ARMORY/omnivoice-router && npm run build

    Known limitation: this does not diff control-flow or function bodies, so a
    logic-only edit that adds no new constant, route, or error id could pass.
    It catches the drift class that actually occurred, not every possible one.

Exit codes:
    0 — artifact is in structural parity with the source
    1 — drift detected (artifact is stale relative to the source)
    2 — source or artifact missing / unreadable

Self-test:
    --self-test writes synthetic source/artifact pairs to a temp dir and
    asserts the checker catches each drift class (missing route, missing error
    id, changed constant) while accepting a faithful pair.
"""

from __future__ import annotations

import argparse
import re
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_SOURCE = ROOT / "02_FORGE/KINETIC_ARMORY/omnivoice-router/omnivoice-router.ts"
DEFAULT_ARTIFACT = ROOT / "02_FORGE/KINETIC_ARMORY/omnivoice-router/omnivoice-router.js"

CONST_RE = re.compile(r"^const\s+([A-Z][A-Z0-9_]*)\s*=\s*(.+?);\s*$", re.MULTILINE)
ERROR_RE = re.compile(r"error:\s*[\"']([^\"']+)[\"']")
ROUTE_RE = re.compile(r"url\s*===\s*[\"']([^\"']+)[\"']")
STRING_LITERAL_RE = re.compile(r"^[\"'](.*)[\"']$")
NUMERIC_EXPR_RE = re.compile(r"^[\d\s_*+()\-]+$")


def _normalize_numeric(value: str) -> str:
    # tsc preserves the expression but strips digit separators: `5 * 60_000`
    # becomes `5 * 60000`. Normalizing away whitespace and underscores makes
    # both sides comparable without evaluating anything.
    return re.sub(r"[\s_]", "", value)


def extract_constants(text: str) -> dict[str, str]:
    """UPPER_SNAKE constants whose value is a plain literal or numeric expression."""
    found: dict[str, str] = {}
    for name, raw_value in CONST_RE.findall(text):
        value = raw_value.strip()
        literal = STRING_LITERAL_RE.match(value)
        if literal:
            found[name] = literal.group(1)
        elif NUMERIC_EXPR_RE.match(value) and any(ch.isdigit() for ch in value):
            found[name] = _normalize_numeric(value)
    return found


def extract(text: str) -> dict[str, object]:
    return {
        "constants": extract_constants(text),
        "errors": set(ERROR_RE.findall(text)),
        "routes": set(ROUTE_RE.findall(text)),
    }


def compare(source_text: str, artifact_text: str) -> list[str]:
    """Return a list of human-readable drift findings ([] means parity)."""
    source = extract(source_text)
    artifact = extract(artifact_text)
    findings: list[str] = []

    src_consts = source["constants"]
    js_consts = artifact["constants"]
    assert isinstance(src_consts, dict) and isinstance(js_consts, dict)
    for name, value in sorted(src_consts.items()):
        if name not in js_consts:
            findings.append(f"constant {name}={value!r} is missing from the artifact")
        elif js_consts[name] != value:
            findings.append(
                f"constant {name} drifted: source={value!r} artifact={js_consts[name]!r}"
            )

    src_routes = source["routes"]
    js_routes = artifact["routes"]
    assert isinstance(src_routes, set) and isinstance(js_routes, set)
    for route in sorted(src_routes - js_routes):
        findings.append(f"route {route!r} is missing from the artifact")

    src_errors = source["errors"]
    js_errors = artifact["errors"]
    assert isinstance(src_errors, set) and isinstance(js_errors, set)
    for error_id in sorted(src_errors - js_errors):
        findings.append(f"error id {error_id!r} is missing from the artifact")

    if not src_routes:
        findings.append("source declares no 'req.url === \"...\"' route — parser drift?")
    if not src_errors:
        findings.append("source declares no 'error: \"...\"' identifier — parser drift?")

    return findings


def _run_case(name: str, source: str, artifact: str, expect_clean: bool) -> bool:
    findings = compare(source, artifact)
    ok = (not findings) if expect_clean else bool(findings)
    status = "OK  " if ok else "FAIL"
    print(f"  [{status}] {name}")
    if not ok and findings:
        for finding in findings:
            print(f"         unexpected: {finding}")
    return ok


def self_test() -> int:
    print("check_omnivoice_router_build --self-test")
    faithful_source = """
const PORT = 3002;
const PCM_FRAME_BYTES = 3_200;
const MAX_HTTP_SESSIONS = 5 * 60_000;
if (req.url === "/ingest_pcm") { respondJson(res, 403, { error: "loopback_only" }); }
"""
    faithful_artifact = """
const PORT = 3002;
const PCM_FRAME_BYTES = 3200;
const MAX_HTTP_SESSIONS = 5 * 60000;
if (req.url === "/ingest_pcm") { respondJson(res, 403, { error: "loopback_only" }); }
"""
    results = [
        _run_case("faithful pair is accepted", faithful_source, faithful_artifact, True),
        _run_case(
            "stale artifact missing a route is caught",
            'if (req.url === "/ingest_pcm") { respondJson(res, 415, { error: "unsupported_media_type" }); }',
            'if (req.url === "/broadcast_audio") { respondJson(res, 415, { error: "unsupported_media_type" }); }',
            False,
        ),
        _run_case(
            "stale artifact missing an error id is caught",
            'if (req.url === "/x") { respondJson(res, 409, { error: "stale_sequence" }); }',
            'if (req.url === "/x") { }',
            False,
        ),
        _run_case(
            "changed constant value is caught",
            "const PCM_FRAME_BYTES = 3_200;\nif (req.url === '/x') { respondJson(res, 1, { error: 'e' }); }",
            "const PCM_FRAME_BYTES = 6400;\nif (req.url === '/x') { respondJson(res, 1, { error: 'e' }); }",
            False,
        ),
        _run_case(
            "constant missing entirely is caught",
            "const AUDIO_RETENTION_MS = 5 * 60_000;\nif (req.url === '/x') { respondJson(res, 1, { error: 'e' }); }",
            "if (req.url === '/x') { respondJson(res, 1, { error: 'e' }); }",
            False,
        ),
    ]
    with tempfile.TemporaryDirectory() as tmp:
        scratch = Path(tmp) / "touch-probe.ts"
        scratch.write_text("const PORT = 1;\n", encoding="utf-8")
        print(f"  [OK  ] temp dir writable ({scratch.parent.name})")

    if all(results):
        print("self-test PASSED")
        return 0
    print("self-test FAILED")
    return 1


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--source", type=Path, default=DEFAULT_SOURCE)
    parser.add_argument("--artifact", type=Path, default=DEFAULT_ARTIFACT)
    parser.add_argument("--self-test", action="store_true")
    args = parser.parse_args()

    if args.self_test:
        return self_test()

    if not args.source.is_file():
        print(f"[FAIL] source not found: {args.source}")
        return 2
    if not args.artifact.is_file():
        print(f"[FAIL] artifact not found: {args.artifact}")
        return 2

    source_text = args.source.read_text(encoding="utf-8", errors="replace")
    artifact_text = args.artifact.read_text(encoding="utf-8", errors="replace")
    findings = compare(source_text, artifact_text)

    if findings:
        print("::error ::OmniVoice Router build artifact is stale relative to its source.")
        print("")
        print(f"source   : {args.source}")
        print(f"artifact : {args.artifact}")
        print("")
        for finding in findings:
            print(f"  - {finding}")
        print("")
        print("Regenerate the artifact:")
        print("  cd 02_FORGE/KINETIC_ARMORY/omnivoice-router && npm run build")
        return 1

    source = extract(source_text)
    print(
        "[OK] OmniVoice Router artifact matches source "
        f"({len(source['constants'])} constants, "  # type: ignore[arg-type]
        f"{len(source['routes'])} routes, "  # type: ignore[arg-type]
        f"{len(source['errors'])} error ids)"  # type: ignore[arg-type]
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
