#!/bin/bash
# SPDX-License-Identifier: MIT

# =========================================================================
# Camelot-OS Phased Safe Deletion Script
# Generated by SwarmExecutor on 2026-08-09
# =========================================================================

echo "========================================================"
echo "🛡️  Camelot-OS Sovereign Branch Cleanup Daemon Active 🛡️"
echo "========================================================"
echo "This script executes safe, interactive, multi-phase branch deletion."
echo "Press Ctrl+C at any time to abort."
echo ""

# Function to confirm action
confirm_phase() {
    read -p "Proceed with $1? [y/N]: " response
    case "$response" in
        [yY][eE][sS]|[yY]) 
            return 0
            ;;
        *)
            return 1
            ;;
    esac
}

# PHASE 1: High Priority Deletions (51 branches)
echo "--------------------------------------------------------"
echo "PHASE 1: High Priority Deletions (Auto-test/Old tasks)"
echo "--------------------------------------------------------"
if confirm_phase "Phase 1 High Priority Deletions"; then
    echo "Executing Phase 1 deletions..."
    # Delete Local High Priority Branches
    git branch -D chore/reconcile-ledger test/forge-ci-verify || true

    # Delete Remote High Priority Branches
    git push origin --delete chore/reconcile-ledger || true
    git push origin --delete jules-10712921885054765292-d021edc9 || true
    git push origin --delete jules-11353948197766782987-5b078e57 || true
    git push origin --delete jules-11807086193072475054-d9d6689d || true
    git push origin --delete jules-13685928328849046027-950c0a8f || true
    git push origin --delete jules-13798903871659040487-32fb6bd6 || true
    git push origin --delete jules-13958884887311147722-7e92e43e || true
    git push origin --delete jules-14652323868499434249-db72953e || true
    git push origin --delete jules-14848844915556885788-f7e9b184 || true
    git push origin --delete jules-14949496074366286282-7c16651d || true
    git push origin --delete jules-15354752064805903781-46af7feb || true
    git push origin --delete jules-15408803311988145932-db61885b || true
    git push origin --delete jules-15758564067108811629-1c5e7c6f || true
    git push origin --delete jules-15789973257784491136-5e47e24e || true
    git push origin --delete jules-16484606233663719515-3d6edd9b || true
    git push origin --delete jules-16954867155360788401-b9a6d780 || true
    git push origin --delete jules-1696512268705221735-a245b292 || true
    git push origin --delete jules-17401987520319811742-40a6eb99 || true
    git push origin --delete jules-2056914292832214566-011a54f8 || true
    git push origin --delete jules-3364392792934761903-8208ae1c || true
    git push origin --delete jules-5296846773331427150-91c846d0 || true
    git push origin --delete jules-5517508343826941199-9bc351dc || true
    git push origin --delete jules-6323274055993247391-79eaf42b || true
    git push origin --delete jules-64894559662062682-8530e3b8 || true
    git push origin --delete jules-7168714172324585047-beb87e5e || true
    git push origin --delete jules-8119781171244979726-28ea05e6 || true
    git push origin --delete jules-8883852214891331384-2ced3f2b || true
    git push origin --delete jules-8916024630294144460-e82c4530 || true
    git push origin --delete jules-9097159145101957090-1b8edf91 || true
    git push origin --delete jules-9147038741577999041-87dc212a || true
    git push origin --delete jules-98691517388669616-2db83aaf || true
    git push origin --delete jules-excalibur-test-1280965994081389782 || true
    git push origin --delete jules-gradio-app-tests-4157472804854027965 || true
    git push origin --delete jules-judge-parallel-472032001179809695 || true
    git push origin --delete jules-optimize-n1-query-4483458049211543981 || true
    git push origin --delete jules-perf-asyncio-sleep-12970430119974605928 || true
    git push origin --delete jules-refactor-timestamp-prompt-11738935551527523745 || true
    git push origin --delete jules-sky-engine-test-15293304288375034374 || true
    git push origin --delete jules-test-crawl4ai-types-4962781323877147061 || true
    git push origin --delete jules-test-symbolect-651876992947727157 || true
    git push origin --delete jules-testing-improvement-bifrost-reconcile-trust-11712367549379462486 || true
    git push origin --delete jules-tests-regex-cleaner-9506142123268101750 || true
    git push origin --delete jules-wasi-nn-184692821615768005 || true
    git push origin --delete jules/cybertronia-audit-perf-fix-1020804364677132045 || true
    git push origin --delete jules/fix-turboquant-model-loading-11234203320044134643 || true
    git push origin --delete jules/test-mentor-check-system-integrity-16754199266568120075 || true
    git push origin --delete test/bifrost-sidecar-health-8746311169506465205 || true
    git push origin --delete test/forge-ci-verify || true
    git push origin --delete test/symbolect-coverage-15873874727967898634 || true

else
    echo "Phase 1 skipped."
fi

# PHASE 2: Medium Priority Deletions (84 branches)
echo "--------------------------------------------------------"
echo "PHASE 2: Medium Priority Deletions (Old fixes/Violations)"
echo "--------------------------------------------------------"
if confirm_phase "Phase 2 Medium Priority Deletions"; then
    echo "Executing Phase 2 deletions..."
    # Delete Local Medium Priority Branches
    git branch -D backup-before-squash-20260630 docs/readme-infomercial docs/v9000.14-go-live feature/omega-patch-graft merlin-merge-test organize/tier-main shadow/veil-phase2 worktree-agent-a44d8cc993e33457f worktree-boris-audit-fixes worktree-sir-boris-audit-fixes origin || true

    # Delete Remote Medium Priority Branches
    git push origin --delete add-cartridge-id-tests-1216784257257931084 || true
    git push origin --delete add-message-count-chat-14277285771428939337 || true
    git push origin --delete add-message-count-to-chat-router-8603450804105241476 || true
    git push origin --delete add-modal-services-tests-16489036145206591414 || true
    git push origin --delete add-morgana-v2-test-2097903136266958824 || true
    git push origin --delete add-morgana-v2-test-5402673073768593907 || true
    git push origin --delete add-tests-excalibur-process-intent-14135927404880654120 || true
    git push origin --delete add-tests-mentor-log-to-ledger-14282116733650341165 || true
    git push origin --delete add-trivy-scan-tests-11753035978950663509 || true
    git push origin --delete add-validate-schema-tests-639505925902982264 || true
    git push origin --delete claude/agency-blueprint || true
    git push origin --delete claude/camelot-kickbox-voice-slice-tdohyi || true
    git push origin --delete claude/camelot-mvp-velocity || true
    git push origin --delete code-health-message-count-3345096685948863473 || true
    git push origin --delete code-health/async_configs_init_refactor-7058518448408660464 || true
    git push origin --delete code-health/remove-unused-sentence-transformer-2954906048522515501 || true
    git push origin --delete code-health/semantic-chunking-seeder-378773344232086126 || true
    git push origin --delete docs/readme-infomercial || true
    git push origin --delete docs/v9000.14-go-live || true
    git push origin --delete dynamic-property-setting-crawl4ai-8372352184397562380 || true
    git push origin --delete fix-command-injection-2000849602266305572 || true
    git push origin --delete fix-crawl4ai-docstrings-8696734460026442374 || true
    git push origin --delete fix-cybertronia-audit-bucket-swap-17211148199955559408 || true
    git push origin --delete fix-docstrings-html2text-5838074545200597122 || true
    git push origin --delete fix-dynamic-init-crawl4ai-14336680676265809566 || true
    git push origin --delete fix-dynamic-property-setattr-1433400506920013703 || true
    git push origin --delete fix-empty-identifiers-cybertronia-audit-4015430343067583220 || true
    git push origin --delete fix-ffi-policy-tests-14203568147144438578 || true
    git push origin --delete fix-gradio-app-test-coverage-17844256832134393930 || true
    git push origin --delete fix-hardcoded-bifrost-secret-18177839237115205649 || true
    git push origin --delete fix-headless-fallback-17445586500112242865 || true
    git push origin --delete fix-html2text-docstrings-5474628407751768586 || true
    git push origin --delete fix-html2text-indent-16878995707866466549 || true
    git push origin --delete fix-html2text-nested-backticks-8397426638550487000 || true
    git push origin --delete fix-llm-judge-parallel-eval-16272210582149736127 || true
    git push origin --delete fix-message-count-in-chat-11143213117472575830 || true
    git push origin --delete fix-nano-id-node-data-1667943881601948 || true
    git push origin --delete fix-notebook-n1-query-6324145690815902717 || true
    git push origin --delete fix-popup-dom-wrap-3846692534959569212 || true
    git push origin --delete fix-popup-dom-wrap-4383819727612110516 || true
    git push origin --delete fix-qr-pill-shell-injection-13408143116490418551 || true
    git push origin --delete fix-rustdesk-db-sql-injection-12647715023709181572 || true
    git push origin --delete fix-source-chat-message-count-11257016643433811605 || true
    git push origin --delete fix-subprocess-shell-injection-7991819588717786846 || true
    git push origin --delete fix-unused-os-import-8633743796710408667 || true
    git push origin --delete fix-unused-qdrant-import-10235573969520249742 || true
    git push origin --delete fix/27-ci-cli || true
    git push origin --delete fix/27-ci-deps || true
    git push origin --delete fix/27-ci-gate || true
    git push origin --delete fix/27-kernel || true
    git push origin --delete fix/27-wave3 || true
    git push origin --delete fix/switchboard-loop-starvation || true
    git push origin --delete implement-semantic-chunking-394407254782819172 || true
    git push origin --delete main || true
    git push origin --delete optimize-ledger-get-all-data-6663368018217528471 || true
    git push origin --delete optimize-local-intelligence-swarm-16519952185437731430 || true
    git push origin --delete optimize-persona-regex-extraction-18371038111684179291 || true
    git push origin --delete perf-kg-adjacency-list-12174108908236227951 || true
    git push origin --delete perf-n-plus-1-notebooks-14443317359697631709 || true
    git push origin --delete perf-optimize-entity-lookups-1974077836860313724 || true
    git push origin --delete perf-optimize-titan-omega-hybrid-search-5955402442608408848 || true
    git push origin --delete performance-optimize-to-triplets-11106081649217760034 || true
    git push origin --delete security-fix-cribo-exec-injection-4995232960714533557 || true
    git push origin --delete store-grounding-id-in-nodedata-118180024294422394 || true
    git push origin --delete test-excalibur-health-14283041574220699756 || true
    git push origin --delete test-excalibur-health-check-16823162039430748027 || true
    git push origin --delete test-forge-update-map-17017683334329811443 || true
    git push origin --delete test-get-current-timestamp-9573968303562369967 || true
    git push origin --delete test-mentor-sanitize-environment-11096415129807758356 || true
    git push origin --delete test-soul-binder-exception-7914936902133561806 || true
    git push origin --delete test-symbolect-3230868266414198906 || true
    git push origin --delete testing-improvement-schema-8414752517054928438 || true
    git push origin --delete tests-atomic-pattern-9414217993044249278 || true

else
    echo "Phase 2 skipped."
fi

echo ""
echo "🎉 Cleanup Run Complete. Fetching prune to align git state..."
git fetch --all --prune || true
echo "✅ State synchronized."
