#!/bin/bash
# SPDX-License-Identifier: MIT

# =========================================================================
# Camelot-OS Branch Cleanup Validation Script
# Generated by SwarmExecutor on 2026-08-09
# =========================================================================

echo "========================================================"
echo "🔍 Camelot-OS Post-Cleanup Validation Suite 🔍"
echo "========================================================"
echo ""

# Count active branches
total_branches=$(git branch -a | grep -v "HEAD" | wc -l)
echo "Total remaining branches (local + remote): $total_branches"

if [ "$total_branches" -le 25 ]; then
    echo "✅ PASS: Branch count is within boundaries ($total_branches <= 25)."
else
    echo "⚠️  WARN: Branch count exceeds ideal threshold ($total_branches > 25)."
fi

# Check naming compliance
non_compliant_count=0
while read -r branch; do
    cleaned=$(echo "$branch" | sed 's/^[ *]*//' | sed 's/remotes\/origin\///')
    
    # Skip main and master from prefix check
    if [ "$cleaned" == "main" ] || [ "$cleaned" == "master" ]; then
        continue
    fi
    
    compliant=false
    for prefix in "feat/" "fix/" "chore/" "docs/" "perf/" "refactor/" "test/" "ci/" "claude/"; do
        if [[ "$cleaned" == $prefix* ]]; then
            compliant=true
            break
        fi
    done
    
    if [ "$compliant" = false ]; then
        echo "❌ Violator: $cleaned"
        non_compliant_count=$((non_compliant_count + 1))
    fi
done < <(git branch -a | grep -v "HEAD")

echo ""
if [ "$non_compliant_count" -eq 0 ]; then
    echo "✅ PASS: 100% Naming Taxonomy Compliance achieved."
else
    echo "❌ FAIL: Found $non_compliant_count naming taxonomy violations."
fi
