name: Deploy Redis Sentinel

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Ansible
        run: pip install ansible

      - name: Run Ansible Playbook
        run: ansible-playbook -i ansible/inventory.ini ansible/deploy_redis_sentinel.yml
